### ISSUE TITLE
ConcurrentModificationException while starting process

### ISSUE THREAD

**Issue by tsyamamoto** [eclipse-ee4j/glassfish#22612]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 4.1,5.0,5.1.0-RC1
* JDK version:8
* OS:Windows,Linux
* Database:None

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
hk2-config has thread unsafe problems.
Starting GlassFish sometimes hungs up because of ConcurrentModificationException.

<pre>
[2018-11-09T15:09:25.904+0900] [glassfish 5.0] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1541743765904] [levelValue: 800] [[
  GlassFish Server Open Source Edition  5.0.1  (5.1.0-RC1) startup time : Felix (15,000ms), startup services(81,825ms), total(96,825ms)]]

[2018-11-09T15:09:25.905+0900] [glassfish 5.0] [SEVERE] [NCLS-CORE-00019] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1541743765905] [levelValue: 1000] [[
  Shutting down server due to startup exception
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.jvnet.hk2.config.Dom.element(Dom.java:513)
	at org.glassfish.grizzly.config.dom.NetworkListener$Duck.findThreadPool(NetworkListener.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jvnet.hk2.config.Dom.invokeDuckMethod(Dom.java:1105)
	at org.jvnet.hk2.config.Dom.invoke(Dom.java:1056)
	at org.glassfish.config.support.TranslatedConfigView.invoke(TranslatedConfigView.java:107)
	at com.sun.proxy.$Proxy107.findThreadPool(Unknown Source)
	at org.glassfish.grizzly.config.GenericGrizzlyListener.configure(GenericGrizzlyListener.java:286)
	at com.sun.enterprise.v3.services.impl.GrizzlyProxy.initialize(GrizzlyProxy.java:100)
	at com.sun.enterprise.v3.services.impl.GrizzlyService.createNetworkProxy(GrizzlyService.java:567)
	at com.sun.enterprise.v3.services.impl.GrizzlyService.postConstruct(GrizzlyService.java:518)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:327)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:786)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]
</pre> 

stdout
<pre>
C:\glassfish5\glassfish\bin>asadmin start-cluster cluster
Timed out while waiting for command start-instance to complete for: instance
Command start-cluster completed with warnings.

C:\glassfish5\glassfish\bin>asadmin list-clusters
cluster not running
Command list-clusters executed successfully.
</pre>

I believe that synchronization is needed while iterating ArrayList.
```
    /**
     * Returns the child element by name
     * @param name of the element
     * @return child element
     */
    public Dom element(String name) {
        synchronized (this) { // synchrozation is needed even if you don't add or remove elements
            List<Child> children = this.children; // fix the snapshot that we'll work with

            for (Child child : children) {
                if (child.name.equals(name)) {
                    return ((NodeChild) child).dom;
                }
            }
        }
        return null;
    }
```

I found several field variables which are not thread safe on source codes.

org.jvnet.hk2.config.Dom
* attributes
* children
* listeners

org.jvnet.hk2.config.ConfigBean
* optionalFeatures

org.jvnet.hk2.config.ConfigModel
* methodCache

org.jvnet.hk2.config.Transactions
* listeners
* typeListeners

org.jvnet.hk2.config.WriteableView
* changedEvents
* changedAttribute
* changedCollections

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

You can easily reproduce the problem by using debugger.

1. set break points
```
    public Dom element(String name) {
        
        List<Child> children = this.children; // fix the snapshot that we'll work with

        for (Child child : children) {
            if (child.name.equals(name)) {/* set break point here */
                return ((NodeChild) child).dom;
            }
        }
        return null;
    }
```

```
    public synchronized void insertAfter(Dom reference, String name, Dom newNode) {
        // TODO: reparent newNode
        if(name.equals("*"))    name=newNode.model.tagName;
        NodeChild newChild = new NodeChild(name, newNode);

        if (children.size()==0) {
            children = new ArrayList<Child>();
        }
        if(reference==null) {
            children.add(0, newChild);
            newNode.domDescriptor = addWithAlias(getHabitat(), newNode, newNode.getProxyType(), newNode.getKey());
            return;/* set break point here */
        }

        ListIterator<Child> itr = children.listIterator();
        while(itr.hasNext()) {
            Child child = itr.next();
            if (child instanceof NodeChild) {
                NodeChild nc = (NodeChild) child;
                if(nc.dom==reference) {
                    itr.add(newChild);
                    newNode.domDescriptor = addWithAlias(getHabitat(), newNode, newNode.getProxyType(), newNode.getKey());
                    
                    return;/* set break point here */
                }
            }
        }
        throw new IllegalArgumentException(reference+" is not a valid child of "+this+". Children="+children);
    }
```

2. enable debug while starting (suspend=y is needed).
<pre>
   asadmin set cluster.java-config.debug-options=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=${JAVA_DEBUGGER_PORT}
   asadmin set cluster.java-config.debug-enabled=true
</pre>
3. asadmin start-cluster cluster
4. connect to the process by debugger
5. wait until two RunLevelControllerThreads stop at each break point
6. disconnect from the process

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
We cannot start processes safely because it sometimes hangs up.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by romain-grecourt** [comment]
You can submit a PR. You will need to sign the ECA (https://www.eclipse.org/legal/ECA.php) and sign off your commit before it can be merged.

**Comment by bshannon** [comment]
@tsyamamoto is this still a problem for you?  Or did #22939 fix this for you?  Do you have the source code changes that fix this problem?  Can you submit a Pull Request?  If so, please reopen this bug.

Thanks!

**Comment by tsyamamoto** [comment]
#22939 is the bug fix for this problem.
However, I think we also need synchronization for the constructor.

```java
     public Dom(Dom source, Dom parent) {
         this(source.getHabitat(), source.document, parent, source.model);
         List<Child> newChildren = new ArrayList<Child>();
-        for (Child child : source.children) {
-            newChildren.add(child.deepCopy(this));
+        synchronized (source) {
+            for (Child child : source.children) {
+                newChildren.add(child.deepCopy(this));
+            }
         }
````

Plus, I think synchronization for writeTo method in 22939 is large.
So I think we can limit the range of the synchronization as follow.
```java
-        List<Child> localChildren = new ArrayList<Child>(children);
+        List<Child> localChildren;
+        synchronized(this) {
+            localChildren = new ArrayList<Child>(children);
+        }
```

I'd like to submit this,  but I can't reopen this issue.
Could you reopen this issue?
