### ISSUE TITLE
HK2 is breaking Tomcat's graceful shutdown

### ISSUE THREAD

**Issue by igor-bbm** [eclipse-ee4j/glassfish#22664]
Jersey's HK2 is breaking Tomcat's graceful shutdown

## Environment Details
OS: Linux Ubuntu 16.04

Technology stack:
Tomcat 7.0.92, Spring 4.1.6, Jersey 2.27, HK2 2.5.0-b32
----------

I am heavily using async API in my app and I have a need to gracefully shutdown Tomcat. Meaning that I let requests in flight to run to completion while rejecting requests that were issued after the shutdown sequence was initiated.

I am using Tomcat's context property `unloadDelay` to achieve this.

My requests are failing with the following exception:

```
Caused by: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,0,344770564) has been shut down

    at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
    at org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
    at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
    at org.glassfish.jersey.inject.hk2.RequestContext.lambda$findOrCreate$0(RequestContext.java:84)
    at org.glassfish.jersey.internal.inject.ForeignDescriptorImpl.dispose(ForeignDescriptorImpl.java:87)
    at org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.remove(Hk2RequestScope.java:150)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.release(Hk2RequestScope.java:167)
    at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:918)
    at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
    at net.rim.msdp.bbmuser.web.impl.ContactListWebServiceImpl.lambda$getContactList$0(ContactListWebServiceImpl.java:92)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
    ... 25 more      
    Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_0,0,344770564) has been shut down
    at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2393)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:635)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:628)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:646)
    at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
    ... 36 more
```

It seems that glassfish components shutdown sequence prematurely and should respect Tomcat's unload delay.

**Comment by smillidge** [comment]
Why are you reporting this on the GlassFish repo?

**Comment by smillidge** [comment]
This would be better reported on this repo https://github.com/eclipse-ee4j/glassfish-hk2 or on Jersey itself https://github.com/eclipse-ee4j/jersey
