### ISSUE TITLE
quickLook: adminconsole_tests fails 

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/glassfish#22676]
## Environment Details
* GlassFish Version (and build number): EE4J_8 branch, bacf743af

## Problem Description
server log says:
```
[2018-12-18T21:42:29.717+0100] [glassfish 5.0] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=210 _ThreadName=Thread-66] [timeMillis: 1545165749717] [levelValue: 1000] [[
  Exception during lifecycle processing
com.sun.enterprise.module.ResolveError: Not able to locate a unique module by name javax.servlet-api
    at com.sun.enterprise.v3.server.ClassLoaderHierarchyImpl.createApplicationParentCL(ClassLoaderHierarchyImpl.java:148)
    at org.glassfish.deployment.common.DeploymentContextImpl.createClassLoader(DeploymentContextImpl.java:222)
    at org.glassfish.deployment.common.DeploymentContextImpl.createDeploymentClassLoader(DeploymentContextImpl.java:205)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:341)
    at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:382)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:187)
    at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:76)
]]

[2018-12-18T21:42:29.719+0100] [glassfish 5.0] [SEVERE] [NCLS-CORE-00041] [javax.enterprise.system.core] [tid: _ThreadID=210 _ThreadName=Thread-66] [timeMillis: 1545165749719] [levelValue: 1000] [[
  Application deployment failed: Exception while deploying the app [__admingui]]] 
```

## Steps to reproduce
mvn -f appserver/tests/quicklook/pom.xml test -Dglassfish.home=appserver/distributions/glassfish/target/stage/glassfish5/glassfish

## Impact of Issue
admingui is broken

**Comment by romain-grecourt** [comment]
How comes the pipeline is passing currently ? Is this is a false positive ?

**Comment by lukasj** [comment]
no idea, actually just found the difference:
* the glassfish I have has jakarta.servlet-api.jar which has Bundle-SymbolicName in manifest: 'jakarta.servlet-api'
* the glassfish the build job has has Bundle-SymbolicName in manifest: 'javax.servlet-api'

one of us is not on the bleeding edge, so to say....

**Comment by romain-grecourt** [comment]
This means someone has re-released the servlet-api with the same GAV !!!
The pipeline uses a cache that's persistent, meaning you are on the bleeding edge.

**Comment by lukasj** [comment]
fixed by #22677

**Comment by PatrickHuang888** [comment]
why checkout tag 5.1.0 still has this error?

**Comment by romain-grecourt** [comment]
I was able to rebuild the 5.1.0 tag with a fresh maven repository and run the quicklooks tests without error.

**Comment by PatrickHuang888** [comment]
> I was able to rebuild the 5.1.0 tag with a fresh maven repository and run the quicklooks tests without error.
I use tag 5.1.0-RELEASE, but it disappeard now, it sill changing?
and have you noticed tag 5.1.0 actual version is  5.1.1?

**Comment by romain-grecourt** [comment]
I deleted the 5.1.0-RELEASE tag since it was wrong and confusing. The 5.1.0 has a minor issue which seems to be due to a glitch in the release script (@vinayvishal @Tomas-Kraus  FYI), I'll fix the tag manually to point at the previous commit.
