### ISSUE TITLE
WELD-000321: No conversation found to restore for id 1

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/glassfish#22749]
## Environment Details
* GlassFish Version (and build number):V4 or V5

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
I am hitting the following error when the http session is timeout and ViewExpiredException happen and dispatch to the errorpage.

org.jboss.weld.context.NonexistentConversationException: WELD-000321: No conversation found to restore for id 1
at org.jboss.weld.context.AbstractConversationContext.initialize(AbstractConversationContext.java:259)
at org.jboss.weld.context.http.LazyHttpConversationContextImpl.initialize(LazyHttpConversationContextImpl.java:90)
at org.jboss.weld.context.AbstractConversationContext.activate(AbstractConversationContext.java:234)
at org.jboss.weld.jsf.WeldPhaseListener.activateConversations(WeldPhaseListener.java:118)
at org.jboss.weld.jsf.WeldPhaseListener.beforePhase(WeldPhaseListener.java:85)
at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:228)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:99)
at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:121)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:876)
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:739)
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:577)
at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:546)
at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:428)
at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:505)
at org.apache.catalina.core.StandardHostValve.dispatchToErrorPage(StandardHostValve.java:699)
at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:306)

It works fine in the WildFly.
[jsfConversationNone.zip](https://github.com/eclipse-ee4j/glassfish/files/3088268/jsfConversationNone.zip)

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
1.unzip and deploy the attached app
2.http://localhost:28080/jsfConversationNone/index.xhtml
3.click at the button "go to the page1 and conversation start"
4.waiting for the timeout(1 minutes)
5.click at the button "Go to Page2"

**Comment by smillidge** [comment]
and what are you expecting to happen? What do you consider correct behaviour?

**Comment by caim2015** [comment]
> 
> 
> and what are you expecting to happen? What do you consider correct behaviour?

I just want to normally display the errorpage when the session is timeout and ViewExpiredException occurs.

**Comment by caim2015** [comment]
Hi, what do you think of this issue?

**Comment by caim2015** [comment]
Hi, what do you think of this issue?

**Comment by caim2015** [comment]
Hi,I’m so sorry to message you again.
Can you spare me a few minutes about the issue.
It works fine in the WildFly,so this is likely an issue with GF integration.

**Comment by TakahideYamazaki** [comment]
What do you think about this matter? Please present your views.

**Comment by caim2015** [comment]
> and what are you expecting to happen? What do you consider correct behaviour?

 I think the correct behaviour should be to display the errorpage normally.
The reason why the error happens is that the conversation is being propagated on the errorpage even though the conversation no longer exists.
Can you spare me a few minutes about the issue？It is very easy to reproduce
