### ISSUE TITLE
Transaction timeout setting ignored / hard coded to 120 sec

### ISSUE THREAD

**Issue by teo-marinescu** [eclipse-ee4j/glassfish#22741]
## Environment Details
* GlassFish Version (and build number): 5.1.0  (build default-private)
* JDK version: 1.8.0_181
* OS: Linux RHEL 6.10 / Windows 7
* Database: Oracle 12

----------

## Problem Description
In GlassFish 5.x when a transaction runs for longer than 120 seconds it will timeout and be marked for rollback regardless of the Transaction Timeout set in Configurations -> server-config -> Transaction Service -> Transaction Timeout.
I have tried setting this to another value than the default 0 thinking that only the 0 (disable) is ignored but that didn't work.
This was working well in GlassFish 4.x. I was even able to reproduce the current behavior in GF4.x by setting the timeout to 120 seconds, but in that case it is the expected behavior.
The problem is easily reproducible.

javax.ejb.TransactionRolledbackLocalException: Client's transaction aborted
	at com.sun.ejb.containers.EJBContainerTransactionManager.useClientTx(EJBContainerTransactionManager.java:337)
	at com.sun.ejb.containers.EJBContainerTransactionManager.preInvokeTx(EJBContainerTransactionManager.java:231)
	at com.sun.ejb.containers.BaseContainer.preInvokeTx(BaseContainer.java:4534)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:1996)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:186)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:64)

I have found the potential problem in the code too. It seems that some cmtTimeoutInSeconds is initialized to 120 here https://github.com/eclipse-ee4j/glassfish/blob/ab2f985d2a4f3e6946992f4e9957699c58ed0b28/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/EJBContainerTransactionManager.java#L66 but I'm unsure where it fails to re-read this from the config or if it is done at all.

## Steps to reproduce
1. Turn transaction monitoring on in Configurations -> Monitoring -> Transaction Service.
2. Run a JPA transaction that takes longer than 120 seconds. 
3a. Monitor the transaction status in Monitoring Data
3b. Alternatively when the transaction should be completed, it will throw  javax.ejb.TransactionRolledbackLocalException: Client's transaction aborted

## Impact of Issue
We have some transactions that run for this long or longer sometimes and we are currently in the testing phase for upgrading from GlassFish 4.1.1 to 5.1.0, but this is a showstopper for us.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by teo-marinescu** [comment]
Hey guys! Anyone had the chance to take a look at this one?
Do you need any extra information?

**Comment by vlumi** [comment]
Would you happen to have a minimal project for reproducing the issue, to test and debug this?

**Comment by petbar72** [comment]
Any update on this issue? 
Thanks.

**Comment by arcovandervelden** [comment]
We're running into the same problem upgrading from Glassfish 4 to 5.1.
Any idea when this will be fixed ?

**Comment by dandyfresh** [comment]
I have the same problem... Any update?

**Comment by sabbik** [comment]
I have the same problem... Please let us know how can we fix that ??

**Comment by hberton** [comment]
Any solution?

**Comment by arjantijms** [comment]
Let's target this to 6.2.4 and finally try to fix it.

**Comment by zistrong** [comment]
this bug still haven't fixed in glassfish 5 & 6;
