### ISSUE TITLE
Grizzly OutOfMemory issue.

### ISSUE THREAD

**Issue by Mariselvam14** [eclipse-ee4j/glassfish#22817]
## Environment Details
* GlassFish Version (and build number): Version 5.0.1
* JDK version: Open JDK 8_192
* OS: Linux
* Database: Oracle

----------

## Problem Description
Seems like Grizzly is taking too much Heap and ends up with OutOfMemory every 24hours or 48 hours

  GRIZZLY0013: Exception during FilterChain execution
java.lang.OutOfMemoryError: Java heap space
        at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
        at sun.security.ssl.OutputRecord.<init>(OutputRecord.java:94)
        at sun.security.ssl.EngineOutputRecord.<init>(EngineOutputRecord.java:61)
        at sun.security.ssl.HandshakeOutStream.<init>(HandshakeOutStream.java:62)
        at sun.security.ssl.Handshaker.activate(Handshaker.java:573)
        at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:730)
        at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:757)
        at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1137)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)

 

## Impact of Issue
Trying to upgrade from Glassfish 4 to Glassfish 5.
We are running Glassfish 5 on Production.

**Comment by smillidge** [comment]
Have you done a heap dump to see what classes are taking up memory in your server? The fact Grizzly gets the OOME does not mean Grizzly is taking up the memory.

**Comment by BrianAntao** [comment]
I am facing this exact same issue. and we are using the same glassfish version but Oracle JDK
Can we have some more in depth investigations.

**Comment by BrianAntao** [comment]
[2020-03-31T07:04:43.471-0400] [glassfish 5.0] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=85 _ThreadName=http-listener-2(6)
] [timeMillis: 1585652683471] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.OutOfMemoryError: Java heap space
        at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
        at sun.security.ssl.OutputRecord.<init>(OutputRecord.java:94)
        at sun.security.ssl.EngineOutputRecord.<init>(EngineOutputRecord.java:61)
        at sun.security.ssl.HandshakeOutStream.<init>(HandshakeOutStream.java:62)
        at sun.security.ssl.Handshaker.activate(Handshaker.java:573)
        at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:730)
        at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:757)
        at org.glassfish.grizzly.ssl.SSLBaseFilter$SSLTransportFilterWrapper.handleRead(SSLBaseFilter.java:1137)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)
]]

[2020-03-31T07:05:02.527-0400] [glassfish 5.0] [WARNING] [] [org.glassfish.grizzly.threadpool.AbstractThreadPool] [tid: _ThreadID=85 _ThreadName=http-listener-2(6)]
 [timeMillis: 1585652702527] [levelValue: 900] [[
  GRIZZLY0011: Uncaught exception on thread Thread[http-listener-2(6),5,main]
java.lang.OutOfMemoryError: Java heap space
]]

**Comment by romain-grecourt** [comment]
This kind of issue needs a heap dump analysis, the stack trace doesn't mean much.

**Comment by BrianAntao** [comment]
Here's the Heap Histogram:

Attaching to process ID 673, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.202-b08
Object Histogram:

num       #instances    #bytes  Class description
--------------------------------------------------------------------------
1:              131706  914151792       byte[]
2:              159104  16078968        char[]
3:              135540  10670568        java.lang.Object[]
4:              125454  6021792 org.glassfish.grizzly.filterchain.DefaultFilterChain$FilterStateElement[]
5:              42647   4209848 int[]
6:              254271  4068336 java.lang.Object
7:              17915   3869640 sun.security.ssl.ServerHandshaker
8:              157140  3771360 java.lang.String
9:              36175   2889656 short[]
10:             85250   2728000 java.util.LinkedList
11:             82348   2635136 java.util.HashMap$Node
12:             17923   2437528 org.glassfish.grizzly.nio.transport.TCPNIOConnection
13:             17915   2436440 sun.security.ssl.SSLEngineImpl
14:             66196   2118272 java.util.concurrent.ConcurrentHashMap$Node
15:             17923   2007376 sun.nio.ch.SocketChannelImpl
16:             35830   2006480 sun.security.ssl.EngineOutputRecord
17:             19706   1806768 java.util.HashMap$Node[]
18:             74671   1792104 java.util.ArrayList
19:             71754   1722096 java.util.concurrent.ConcurrentLinkedQueue$Node
20:             71708   1720992 java.util.concurrent.ConcurrentLinkedQueue
21:             17122   1506736 java.lang.reflect.Method
22:             37666   1506640 java.util.LinkedHashMap$Entry
23:             35837   1433480 org.glassfish.grizzly.asyncqueue.TaskQueue
24:             12162   1392080 java.lang.Class
25:             53781   1290744 java.net.InetSocketAddress$InetSocketAddressHolder
26:             35987   1155248 java.nio.ByteBuffer[]
27:             35876   1148032 java.net.InetAddress$InetAddressHolder
28:             35842   1146944 org.glassfish.grizzly.memory.AbstractBufferArray$PosLim[]
29:             35842   1146944 org.glassfish.grizzly.memory.ByteBufferArray
30:             35833   1146656 sun.security.ssl.ProtocolList
31:             17915   1146560 sun.security.ssl.EngineInputRecord
32:             17921   1003576 org.glassfish.grizzly.ssl.SSLConnectionContext
33:             17915   1003240 sun.security.ssl.InputRecord
34:             24868   994720  java.util.WeakHashMap$Entry
35:             3761    950632  java.util.concurrent.ConcurrentHashMap$Node[]
36:             35869   860856  java.net.Inet4Address
37:             53781   860496  java.net.InetSocketAddress
38:             35851   860424  org.glassfish.grizzly.utils.Holder$3
39:             17922   860256  org.glassfish.grizzly.filterchain.DefaultFilterChain$FilterStateElement[][]
40:             13151   736456  java.util.LinkedHashMap
41:             17928   717120  sun.nio.ch.SelectionKeyImpl
42:             17923   716920  sun.nio.ch.SocketAdaptor
43:             17922   716880  org.glassfish.grizzly.utils.IdleTimeoutFilter$IdleRecord
44:             17915   716600  sun.security.ssl.HandshakeHash
45:             20617   673136  java.lang.String[]
46:             13534   649632  java.util.HashMap

**Comment by BrianAntao** [comment]
From the jmat heap histogram of the crashed application NONE of our application objects are leaking !
It might be an issue of the filterChain configuraton or some other configuration looks like.

**Comment by romain-grecourt** [comment]
You can use "Eclipse MAT" (memory analysis toolkit) and run the leak suspect report.

The report shows suspected problems related to the GC roots identified in the heap dump.
If you click on the details for each suspected problem, you can see the underlying GC root in various views, you can also directly run queries for that GC root.

Can you run the report and share screenshots of the details page for each suspected problem ?
This would be very useful as a starting point.

**Comment by BrianAntao** [comment]
Hi Romain,
      Many thanks for your assistance is there anyway I can get you the
heapdump it is huge as you can imagine !

Cheers,
      --Brian

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BrianAntao** [comment]
![image](https://user-images.githubusercontent.com/62995607/78251983-0bf50e00-74ea-11ea-8328-66bc254128b7.png)

**Comment by BrianAntao** [comment]
![image](https://user-images.githubusercontent.com/62995607/78252155-4e1e4f80-74ea-11ea-80e2-a7b20ecafc52.png)
