### ISSUE TITLE
Glassfish restart error

### ISSUE THREAD

**Issue by wagachari** [eclipse-ee4j/glassfish#22812]
Problem restarting glassfish 

* GlassFish Version 3.1:
* JDK version: 1.8.0_181
* OS: Windows 7

ERROR: Bundle org.glassfish.metro.webservices-api-osgi [2]: Error starting file:/apps/glassfish3/glassfish/modules/endorsed/webservices-api-osgi.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle org.glassfish.metro.webservices-api-osgi [2]: Unable to resolve 2.0: missing requirement [2.0] package; (&(package=javax.xml.bind)(version>=2.2.0)) [caused by: Unable to resolve 3.0: missing requirement [3.0] package; (package=javax.activation)])
org.osgi.framework.BundleException: Unresolved constraint in bundle org.glassfish.metro.webservices-api-osgi [2]: Unable to resolve 2.0: missing requirement [2.0] package; (&(package=javax.xml.bind)(version>=2.2.0)) [caused by: Unable to resolve 3.0: missing requirement [3.0] package; (package=javax.activation)]
	at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3443)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1727)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1156)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
ERROR: Bundle jaxb-api [3]: Error starting file:/apps/glassfish3/glassfish/modules/endorsed/jaxb-api-osgi.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle jaxb-api [3]: Unable to resolve 3.0: missing requirement [3.0] package; (package=javax.activation))
org.osgi.framework.BundleException: Unresolved constraint in bundle jaxb-api [3]: Unable to resolve 3.0: missing requirement [3.0] package; (package=javax.activation)
	at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3443)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1727)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1156)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
ERROR: Bundle org.glassfish.core.glassfish [31]: Error starting file:/apps/glassfish3/glassfish/modules/glassfish.jar (org.osgi.framework.BundleException: Activator start error in bundle org.glassfish.core.glassfish [31].)
java.lang.NoClassDefFoundError: com/sun/enterprise/module/bootstrap/BootException
	at com.sun.enterprise.glassfish.bootstrap.osgi.GlassFishMainActivator.start(GlassFishMainActivator.java:103)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1835)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1752)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1156)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.enterprise.module.bootstrap.BootException not found by org.glassfish.core.glassfish [31]
	at org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:787)
	at org.apache.felix.framework.ModuleImpl.access$400(ModuleImpl.java:71)
	at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1768)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
ERROR: Bundle com.sun.enterprise.osgi-adapter [65]: Error starting file:/apps/glassfish3/glassfish/modules/osgi-adapter.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle com.sun.enterprise.osgi-adapter [65]: Unable to resolve 65.0: missing requirement [65.0] package; (&(package=com.sun.enterprise.module)(version>=1.1.0)) [caused by: Unable to resolve 125.0: missing requirement [125.0] package; (&(package=org.jvnet.hk2.config)(version>=1.1.0)) [caused by: Unable to resolve 47.0: missing requirement [47.0] package; (package=javax.management)]])
org.osgi.framework.BundleException: Unresolved constraint in bundle com.sun.enterprise.osgi-adapter [65]: Unable to resolve 65.0: missing requirement [65.0] package; (&(package=com.sun.enterprise.module)(version>=1.1.0)) [caused by: Unable to resolve 125.0: missing requirement [125.0] package; (&(package=org.jvnet.hk2.config)(version>=1.1.0)) [caused by: Unable to resolve 47.0: missing requirement [47.0] package; (package=javax.management)]]
	at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3443)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1727)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1156)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:97)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:55)
Caused by: org.glassfish.embeddable.GlassFishException: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:164)
	at org.glassfish.embeddable.GlassFishRuntime._bootstrap(GlassFishRuntime.java:157)
	at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:110)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:112)
	... 6 more
Caused by: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.getGlassFishRuntime(OSGiGlassFishRuntimeBuilder.java:202)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:162)
	... 9 more
Error stopping framework: java.lang.NullPointerException
java.lang.NullPointerException
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher$1.run(GlassFishMain.java:203)
Command start-domain failed.
The DAS was stopped.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by bshannon** [comment]
GlassFish 3.1 is very old, and not supported on JDK 1.8.
If you can reproduce this problem on GlassFish 5.1, reopen this bug.
