### ISSUE TITLE
JDK11 have removed the com.sun.jndi.cosnaming package referenced by GlassFish in these implementations.

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/glassfish#22878]
Starting GlassFish(developed on 5.1.0-run-with-JDK11) on OpenJDK 11.0.2 and deploying a simple EJB application resulted in the following error:
```
Exception while loading the app : EJB Container initialization error
java.lang.RuntimeException: IIOP Protocol Manager initialization failed.  Possible cause is that ORB is not available in this container
(snip)
Caused by: java.lang.RuntimeException: Orb initialization erorr
(snip)
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.cosnaming.CNCtxFactory [Root exception is java.lang.ClassNotFoundException: com.sun.jndi.cosnaming.CNCtxFactory]
(snip)
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.cosnaming.CNCtxFactory
(snip)
```
  
This appears to be caused by the removal of the CORBA implementation included in rt.jar from OpenJDK in accordance with JEP 320.  
  
On the other hand, Orb (glassfish-corba) had this package until version 4.1.1-b001 but removed it at 4.1.1-b002, probably due to a duplicate implementation overlapped with JDK at the time.  
I was able to get around this by getting some of the sources into Orb from glassfish-corba-4.1.1-b001, but the license for this code is GPLv2...  
 - download the source code from: https://github.com/javaee/glassfish-corba/tree/glassfish-corba-4.1.1-b001  
 - temporary changes: https://github.com/hs536/orb/commit/14ba92c8dad55b8d810ca68bc3e2743b87037be9  
  
I’m wondering who (and how) should implement the com.sun.jndi.cosnaming package, but it's not clear yet.    
  
## ■error reference
* command line: (helloEJB3.jar is a very simple EJB app)
```
$ glassfish5/glassfish/bin/asadmin deploy helloEJB3.jar 
remote failure: Error occurred during deployment: Exception while loading the app : EJB Container initialization error. Please see server.log for more details.
Command deploy failed.
```
* server.log:
```
[2020-01-16T11:46:50.207+0900] [glassfish 5.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=54 _ThreadName=admin-listener(2)] [timeMillis: 1579142810207] [levelValue: 1000] [[
  Exception while loading the app]]

[2020-01-16T11:46:50.220+0900] [glassfish 5.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=54 _ThreadName=admin-listener(2)] [timeMillis: 1579142810220] [levelValue: 1000] [[
  Exception while loading the app : EJB Container initialization error
java.lang.RuntimeException: IIOP Protocol Manager initialization failed.  Possible cause is that ORB is not available in this container
	at com.sun.ejb.containers.BaseContainer.initializeProtocolManager(BaseContainer.java:879)
	at com.sun.ejb.containers.BaseContainer.<init>(BaseContainer.java:633)
	at com.sun.ejb.containers.AbstractSingletonContainer.<init>(AbstractSingletonContainer.java:103)
	at com.sun.ejb.containers.CMCSingletonContainer.<init>(CMCSingletonContainer.java:52)
	at com.sun.ejb.containers.SingletonContainerFactory.createContainer(SingletonContainerFactory.java:44)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:198)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:267)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:75)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:182)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:289)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:472)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:195)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:516)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:512)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:511)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:542)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:534)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:533)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1441)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:86)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1699)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:384)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:353)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:150)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:155)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:439)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Orb initialization erorr
	at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:167)
	at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getProtocolManager(GlassFishORBHelper.java:207)
	at com.sun.ejb.containers.BaseContainer.initializeProtocolManager(BaseContainer.java:874)
	... 71 more
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.cosnaming.CNCtxFactory [Root exception is java.lang.ClassNotFoundException: com.sun.jndi.cosnaming.CNCtxFactory]
	at com.sun.enterprise.naming.GlassFishNamingBuilder.createInitialContextFactory(GlassFishNamingBuilder.java:103)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:727)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
	at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.initializeRemoteNamingSupport(GlassfishNamingManagerImpl.java:142)
	at org.glassfish.enterprise.iiop.api.GlassFishORBHelper.getORB(GlassFishORBHelper.java:159)
	... 73 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.cosnaming.CNCtxFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.sun.enterprise.naming.GlassFishNamingBuilder.loadClass(GlassFishNamingBuilder.java:128)
	at com.sun.enterprise.naming.GlassFishNamingBuilder.createInitialContextFactory(GlassFishNamingBuilder.java:96)
	... 79 more
]]
```

**Comment by russgold** [comment]
I see that I had copied the COSNaming service into the ORB in Dec 2016, but later had to remove it. I don’t recall the discussions, but it may well have had to do with the license. I’m trying to find the discussions, hoping that at least some were in email.

**Comment by hs536** [comment]
Jakarta EE 8 requires GlassFish 5.1 to support COSNaming service.
(https://jakarta.ee/specifications/platform/8/platform-spec-8.html)
```
A Jakarta EE product must provide a COSNaming service to support the Jakarta Enterprise Beans interoperability requirements. It must be possible to access this COSNaming service using the Java IDL COSNaming APIs. Applications with appropriate privileges must be able to lookup objects in the COSNaming service. COSNaming is defined in the Interoperable Naming Service specification, available at http://www.omg.org/cgi-bin/doc?formal/2000-06-19 .
```
So, that means... if the packages have been removed for licensing reasons, we need to implement a new COSNaming service to make Glassfish 5.1 compliant with Jakarta EE 8 with JDK 11...?

**Comment by hs536** [comment]
This issue is also relevant for GlassFish 6.X because current EJB container implementations require COSNaming services.

**Comment by hs536** [comment]
See also: https://www.eclipse.org/lists/glassfish-dev/msg00150.html

**Comment by smillidge** [comment]
@hs536 or @russgold can you link to the commit on the orb project that removes the COSNaming service?

**Comment by hs536** [comment]
These were done before the migration to Eclipse Foundation:
 -   copy: https://github.com/javaee/glassfish-corba/commit/2c1f6017185d6fd77d1226d8752a77840f0f7ee6#diff-ed4110229df2408dca6c82a0d3f76792
 - remove: https://github.com/javaee/glassfish-corba/commit/0e33c4db443fe222bf47ded0a1dccf20155eb55d#diff-ed4110229df2408dca6c82a0d3f76792

**Comment by smillidge** [comment]
@hs536 thanks for the commits. @bshannon can you pick this up? I assigned the issue.

**Comment by bshannon** [comment]
Yes, I've started looking into it.

**Comment by bshannon** [comment]
We've resolved this at the Oracle side.  A CQ will be submitted shortly.

**Comment by bshannon** [comment]
The CQ is here: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21779

**Comment by bshannon** [comment]
This is in Eclipse's hands for the moment, but once they approve the CQ it will
be up to Russ to integrate it into the GlassFish ORB repo.  So, I've reassigned
this to Russ to finish.

**Comment by smillidge** [comment]
CQ is approved @russgold is this merged into upstream CORBA?

**Comment by russgold** [comment]
I have not gotten to it yet, no.

**Comment by smillidge** [comment]
I've raised a PR of the code contribution in the CQ https://github.com/eclipse-ee4j/orb/pull/94

@russgold can you approve?

**Comment by smillidge** [comment]
4.2.2-M1 is now staged in jakarta.oss. This incorporates the COS Naming code donated to the Eclipse foundation.
