### ISSUE TITLE
"getGroups" access denied error on Security API TCK run with glassfish 6

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23130]
Security API TCK run, glassfish server logs has "java.security.AccessControlException: access denied (jakarta.security.enterprise.identitystore.IdentityStorePermission getGroups)"
--------------------------

## Environment Details
* GlassFish Version (and build number):6.0 M1
* JDK version: 1.8
* OS:Linux
* Database: Derby

----------------------

Full Stack Trace:
java.security.AccessControlException: access denied ("jakarta.security.enterprise.identitystore.IdentityStorePermission" "getGroups")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.glassfish.soteria.identitystores.LdapIdentityStore.getCallerGroups(LdapIdentityStore.java:137)
	at org.glassfish.soteria.identitystores.LdapIdentityStore$Proxy$_$$_WeldClientProxy.getCallerGroups(Unknown Source)
	at com.sun.ts.tests.securityapi.idstore.idstorepermission.CustomIdentityStoreHandler.validate(CustomIdentityStoreHandler.java:144)
	at com.sun.ts.tests.securityapi.idstore.idstorepermission.CustomIdentityStoreHandler$Proxy$_$$_WeldClientProxy.validate(Unknown Source)
	at com.sun.ts.tests.securityapi.idstore.common.DefaultHamForIDStore.validateRequest(DefaultHamForIDStore.java:67)
	at org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule.validateRequest(HttpBridgeServerAuthModule.java:89)
	at org.glassfish.soteria.mechanisms.jaspic.DefaultServerAuthContext.validateRequest(DefaultServerAuthContext.java:52)
	at com.sun.web.security.RealmAdapter.validate(RealmAdapter.java:1651)
	at com.sun.web.security.RealmAdapter.invokeAuthenticateDelegate(RealmAdapter.java:1509)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:555)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:579)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:555)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:73)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.lang.Thread.run(Thread.java:748)
]]

**Comment by smillidge** [comment]
@arjantijms can you take this as it relates to Soteria?
