### ISSUE TITLE
failures with CDI porting kit for glassfish.

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23149]
We have upgraded cditck-porting kit for glassfish with Jakarta EE 9 technologies and CDI TCK 3.0.
Latest Jenkins run for the porting kit can be found here - https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/57/
We have 1,833 tests run, 16 failures and 24 skipped test with latest run.
For 8 test failure, there are CDI deployment error as follows:
Details of CDI deployment error as follows:
----------------

org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  class org.jboss.cdi.tck.tests.interceptors.definition.inheritance.broken.binding.Messerschmitt
    Exception while loading the app : CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  class org.jboss.cdi.tck.tests.interceptors.definition.inheritance.broken.binding.Messerschmitt
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  class org.jboss.cdi.tck.tests.interceptors.definition.broken.finalClassInterceptor.FinalClassClassLevelMissile
    Exception while loading the app : CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  class org.jboss.cdi.tck.tests.interceptors.definition.broken.finalClassInterceptor.FinalClassClassLevelMissile
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  class org.jboss.cdi.tck.tests.interceptors.definition.broken.finalClassInterceptor.FinalClassMethodLevelMissile
    Exception while loading the app : CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  class org.jboss.cdi.tck.tests.interceptors.definition.broken.finalClassInterceptor.FinalClassMethodLevelMissile
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final:  InjectionTarget for Managed Bean [class org.jboss.cdi.tck.tests.decorators.definition.broken.finalBeanMethod.MockLogger] with qualifiers [@Any @Default]
    Exception while loading the app : CDI deployment failure:WELD-001503: Bean class which has interceptors cannot be declared final: InjectionTarget for Managed Bean [class org.jboss.cdi.tck.tests.decorators.definition.broken.finalBeanMethod.MockLogger] with qualifiers [@Any @Default]

----------------
## Environment Details
* GlassFish Version (and build number): 6.0 M1
* JDK version: 1.8
* OS: Linux
* Database: Derby

----------------

## Steps to reproduce

- git clone https://github.com/eclipse-ee4j/cditck-porting
- cd cditck-porting
- export WORKSPACE=$PWD
- docker/build_cditck.sh
- docker/run_cditck.sh

-------------------

Porting kit Repository link - https://github.com/eclipse-ee4j/cditck-porting
Test report  link- https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/57/testReport/

**Comment by scottmarlow** [comment]
I'll try to reproduce using above steps locally with Podman:
```
podman run -it centos /bin/bash
yum install -y zip maven ant java-1.8.0-openjdk-devel wget vim git unzip

git clone https://github.com/eclipse-ee4j/cditck-porting
cd cditck-porting
export WORKSPACE=$PWD
wget https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip
mv glassfish-6.0.0-SNAPSHOT-nightly.zip latest-glassfish.zip

bash -x docker/build_cditck.sh 2>&1 | tee build.log
bash -x docker/run_cditck.sh 2>&1 | tee run.log
```

**Comment by scottmarlow** [comment]
@RohitKumarJain Do any of the above settings mentioned in my comment look wrong to you?

I do see some tests running and passing but then I get:
```
Total time: 0 seconds
+ ant test 
Buildfile: /tmp/cditck-porting/cdi-tck-glassfish-porting/build.xml

config.v4:
     [exec] CLI306: Warning - The server located at /tmp/cditck-porting/glassfish6/glassfish/domains/domain1 is not running.
     [exec] Command stop-domain executed successfully.
[mvn.dependency] [INFO] Scanning for projects...
[mvn.dependency] [INFO] 
[mvn.dependency] [INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[mvn.dependency] [INFO] Building Maven Stub Project (No POM) 1
[mvn.dependency] [INFO] --------------------------------[ pom ]---------------------------------
[mvn.dependency] [INFO] 
[mvn.dependency] [INFO] --- maven-dependency-plugin:2.8:get (default-cli) @ standalone-pom ---
[mvn.dependency] [INFO] Resolving org.jboss.cdi.tck:cdi-tck-ext-lib:jar:3.0.0-M3 with transitive dependencies
[mvn.dependency] Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/cdi/tck/cdi-tck-ext-lib/3.0.0-M3/cdi-tck-ext-lib-3.0.0-M3.pom
[mvn.dependency] [WARNING] Missing POM for org.jboss.cdi.tck:cdi-tck-ext-lib:jar:3.0.0-M3
[mvn.dependency] Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/cdi/tck/cdi-tck-ext-lib/3.0.0-M3/cdi-tck-ext-lib-3.0.0-M3.jar
[mvn.dependency] [INFO] ------------------------------------------------------------------------
[mvn.dependency] [INFO] BUILD FAILURE
[mvn.dependency] [INFO] ------------------------------------------------------------------------
```

**Comment by gurunrao** [comment]
@scottmarlow  - the difference mentioned above and my local setup is additional M2_HOME. hoping that M2_HoME is not interfering with settings.xml repository configuration.

**Comment by scottmarlow** [comment]
I removed the M2_HOME, I still saw a local failure:
```
BUILD FAILURE
 [mvn.test] [INFO] ------------------------------------------------------------------------
 [mvn.test] [INFO] Total time:  13.449 s
 [mvn.test] [INFO] Finished at: 2020-07-28T01:20:41Z
 [mvn.test] [INFO] ------------------------------------------------------------------------
 [mvn.test] [ERROR] Failed to execute goal on project weld-glassfish-runner-tck11: Could not resolve dependencies for project org.jboss.weld:weld-glassfish-runner-tck11:jar:4.0.0.Alpha3: Failed to collect dependencies at org.jboss.arquillian.container:arquillian-glassfish-managed-6:jar:1.0.0-SNAPSHOT: Failed to read artifact descriptor for org.jboss.arquillian.container:arquillian-glassfish-managed-6:jar:1.0.0-SNAPSHOT: Could not transfer artifact org.jboss.arquillian.container:arquillian-glassfish-managed-6:pom:1.0.0-SNAPSHOT from/to central2 (https://repo1.maven.apache.org/maven2): Transfer failed for https://repo1.maven.apache.org/maven2/org/jboss/arquillian/container/arquillian-glassfish-managed-6/1.0.0-SNAPSHOT/arquillian-glassfish-managed-6-1.0.0-SNAPSHOT.pom: Unknown host repo1.maven.apache.org 
```

**Comment by gurunrao** [comment]
@scottmarlow - I have bumped up glassfish container version. Please pick the latest for github master @ https://github.com/eclipse-ee4j/cditck-porting

Also ran the test run at CI with latest github repo. Details of run can be found @ https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/64/

**Comment by scottmarlow** [comment]
I'm running again locally with Podman (GlassFish 6.0 doesn't work on my laptop directly, I have to run it with Centos under Podman).

It seems like I might be getting further, as I see "running org.jboss.arquillian.container.glassfish.managed_6.CDIJarTestCase" and the contents of a test.war file on the console.  I'll ignore the console for a while and check it again later. :-)

**Comment by scottmarlow** [comment]
Good news, It finished so others should be able to recreate now as well.
```
 [mvn.test] Failed tests:   testWebResourcePassivated(org.jboss.cdi.tck.tests.context.passivating.dependency.resource.webservice.WebResourcePassivationCapableDependencyTest): WELD-000079: Could not instantiate a proxy for a session bean:  Session bean [class org.jboss.cdi.tck.tests.context.passivating.dependency.resource.webservice.PassivatedBean with qualifiers [@Any @Default]; local interfaces are [PassivatedBean]
 [mvn.test]   testRequestScopeActiveDuringWebServiceInvocation(org.jboss.cdi.tck.tests.context.request.ws.RequestContextTest)
 [mvn.test]   arquillianBeforeClass(org.jboss.cdi.tck.tests.context.request.event.jms.RequestScopeEventMessageDeliveryTest): Could not deploy 24366694ab54ddc83623ef655667ac266c465c4.war
 [mvn.test]   arquillianBeforeClass(org.jboss.cdi.tck.tests.context.jms.MessageDrivenBeanContextTest): Could not deploy c5767ddb890bed4cb3d5cedd086106ae17850.war
 [mvn.test]   testSecurityContextPropagation(org.jboss.cdi.tck.tests.event.observer.context.async.enterprise.EnterpriseSecurityContextPropagationInAsyncObserverTest)
 [mvn.test]   arquillianBeforeClass(org.jboss.cdi.tck.tests.extensions.container.event.jms.ContainerEventTest): Could not deploy ca43ae75e93acd53c694137891a6d72a4bfc1.war
 [mvn.test]   testResourceProduced(org.jboss.cdi.tck.tests.implementation.simple.resource.ws.staticProducer.WebServiceResourceStaticProducerFieldTest): expected object to not be null
 [mvn.test]   testInjectionOfWebServiceReference(org.jboss.cdi.tck.tests.implementation.simple.resource.ws.WebServiceReferenceInjectionTest): Exception attempting to inject Env-Prop: org.jboss.cdi.tck.tests.implementation.simple.resource.ws.ResourceProducer/translator@Field-Injectable Resource. Class name = org.jboss.cdi.tck.tests.implementation.simple.resource.ws.ResourceProducer Field name=translator@jakarta.jws.WebServiceRef@@@ into class org.jboss.cdi.tck.tests.implementation.simple.resource.ws.ResourceProducer: Lookup failed for 'java:comp/env/org.jboss.cdi.tck.tests.implementation.simple.resource.ws.ResourceProducer/translator' in SerialContext[myEnv={java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
 [mvn.test]   arquillianBeforeClass(org.jboss.cdi.tck.tests.interceptors.definition.enterprise.jms.MessageDrivenBeanInterceptorInvocationTest): Could not deploy 994731df81c7c6f99a6abf867e3d6b49179ca.war
 [mvn.test]   testInjectionIntoWebServiceEndpoint(org.jboss.cdi.tck.tests.lookup.injection.non.contextual.ws.WebServiceResourceTest): Could not inject members
 [mvn.test]   testResourceBeanTypes(org.jboss.cdi.tck.tests.lookup.injection.non.contextual.ws.WebServiceResourceTest): Could not inject members
 [mvn.test]   testResourceInvocation(org.jboss.cdi.tck.tests.lookup.injection.non.contextual.ws.WebServiceResourceTest): Could not inject members
 [mvn.test]   testInitializerMethodsCalledAfterEEResourceWebServiceRefInjection(org.jboss.cdi.tck.tests.lookup.injection.ws.WebServiceResourceInjectionTest): Exception attempting to inject Env-Prop: org.jboss.cdi.tck.tests.lookup.injection.ws.Alpha/translatorField@Field-Injectable Resource. Class name = org.jboss.cdi.tck.tests.lookup.injection.ws.Alpha Field name=translatorField@jakarta.jws.WebServiceRef@@@ into class org.jboss.cdi.tck.tests.lookup.injection.ws.Alpha: Lookup failed for 'java:comp/env/org.jboss.cdi.tck.tests.lookup.injection.ws.Alpha/translatorField' in SerialContext[myEnv={java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
 [mvn.test]   arquillianBeforeClass(org.jboss.cdi.tck.tests.extensions.lifecycle.processInjectionTarget.WrappedInjectionTargetTest): Could not deploy f5419d7385f74d1fd77f38490fbcc52102f766f.war
 [mvn.test]   testFilterInitCalledAfterResourceInjection(org.jboss.cdi.tck.tests.lookup.injection.non.contextual.WebServiceInjectionIntoNonContextualComponentTest): 404 Not Found for http://localhost:8080/ab28a7f03c159ddc1af43e792c46d4d282d3759/TestFilter2?test=wsresource
 [mvn.test]   testServletInitCalledAfterResourceInjection(org.jboss.cdi.tck.tests.lookup.injection.non.contextual.WebServiceInjectionIntoNonContextualComponentTest): 500 Internal Server Error for http://localhost:8080/ab28a7f03c159ddc1af43e792c46d4d282d3759/TestServlet2?test=wsresource
 [mvn.test]
 [mvn.test] Tests run: 1832, Failures: 16, Errors: 0, Skipped: 24
```
I will look for any clues in my local workspace.

**Comment by scottmarlow** [comment]
@smillidge any suggestions for who could look at the remaining 16 CDI test failures?  

CC @starksm64

**Comment by starksm64** [comment]
I'm working on the 3.0.0 final TCK today, so I will be looking at the state with respect to GF

**Comment by smillidge** [comment]
That would be good as I don't know whether this is a Weld or GlassFish integration of Weld error.

**Comment by starksm64** [comment]
@scottmarlow Try using the staged 3.0.0-RC1 version of the CDI TCK. So far I have not been able to reproduce your podman run, but all these failing tests are obsolete xml webservices tests that should be updated in 3.0.0-RC1.
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/enterprise/cdi-tck-dist/3.0.0-RC1/cdi-tck-dist-3.0.0-RC1-dist.zip

**Comment by starksm64** [comment]
And note that the project settings.xml needs a jakarta staging repo added:

```
        <repository>
          <id>jakarta</id>
          <name>Jakarta Staging Repository</name>
          <url>https://jakarta.oss.sonatype.org/content/repositories/staging/</url>
          <layout>default</layout>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
```

There are some other updates that could simplify this, but since I'm having trouble running this I can't verify them.

**Comment by gurunrao** [comment]
@starksm64  - I tried with CDI TCK RC1, we have better result with only 8 failures now at local dev box. I am currently working on CI build, once CI build is stable will share the link here.
CC - @scottmarlow

**Comment by starksm64** [comment]
Where is the org.glassfish.cdi:gf-cdi-porting-package-tck11:jar:3.0 artifact hosted? I'm stuck on resolving that dependency when running run_cditck.sh:

```
 [mvn.test] [ERROR] Failed to execute goal on project weld-glassfish-runner-tck11: Could not resolve dependencies for project org.jboss.weld:weld-glassfish-runner-tck11:jar:4.0.0.Alpha3: Could not find artifact org.glassfish.cdi:gf-cdi-porting-package-tck11:jar:3.0 in remote (https://jakarta.oss.sonatype.org/content/repositories/staging/) -> [Help 1]
```

**Comment by scottmarlow** [comment]
@starksm64 I'm not sure, https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/69/console has the same failure as you pasted above.

@gurunrao are you also getting the ^ failure on your local machine?

**Comment by gurunrao** [comment]
@starksm64 @scottmarlow  - i am facing the same issue currently, will fix it and let you know once its resolved.

**Comment by gurunrao** [comment]
@starksm64 @scottmarlow - We have 5 failures, 8 skipped tests out of 1,803 tests with CDI  TCK RC1 - Details of CI run can be found @ https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/70/testReport/
The run is from latest master branch @ repo https://github.com/eclipse-ee4j/cditck-porting

**Comment by starksm64** [comment]
It would be good to include all of the glassfish server logs in the run test artifacts that are archived. I'm not matching your run results, but for the jms tests I'm seeing deployment failures like:

Caused by: jakarta.resource.ResourceException: MQRA:EC:Invalid destinationLookup topic_test configured in ActivationSpec of MDB for no JNDI name found

It looks like the TCK expected destinations are not configured to test. There needs to be a topic_test and queue_test destinations configured as indicated in the TCK configuration output:

```
 [mvn.test] INFO: Jakarta CDI 3.0 TCK Configuration
 [mvn.test] -----------------
 [mvn.test] 	Beans: org.glassfish.weld.tck.BeansImpl@2d801d8
 [mvn.test] 	Contexts: org.glassfish.weld.tck.ContextsImpl@b9b97ad
 [mvn.test] 	EL: org.glassfish.weld.tck.ELImpl@2807cf3
 [mvn.test] 	Library dir: target/dependency/lib
 [mvn.test] 	Test DS: jdbc/__default
 [mvn.test] 	Test JMS connection factory: java:comp/DefaultJMSConnectionFactory
 [mvn.test] 	Test JMS queue: queue_test
 [mvn.test] 	Test JMS topic: topic_test
 [mvn.test] 	Test timeout factor: 100
```

The 5 failing tests are all related to jms deployments, so that might be the last thing that needs to be configured to pass.

**Comment by scottmarlow** [comment]
I'm not sure if GlassFish 6.0 supports javax.jms.Topic on GF admin tool, so updating to jakarta.jms.Topic via https://github.com/eclipse-ee4j/cditck-porting/pull/19 (also changed javax.jms.Queue => jakarta.jms.Topic).

**Comment by scottmarlow** [comment]
I'm trying ^ pr#19 locally with Podman, will see if it helps, using updated CDI_TCK_BUNDLE_URL:
```
podman run -it centos /bin/bash
yum install -y zip ant java-1.8.0-openjdk-devel wget vim git unzip

export CDI_TCK_BUNDLE_URL=https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/enterprise/cdi-tck-dist/3.0.0-RC1/cdi-tck-dist-3.0.0-RC1-dist.zip
export CDI_TCK_VERSION=3.0.0-RC1
export GF_BUNDLE_URL=https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip
export ANT_OPTS="-Djavax.xml.accessExternalStylesheet=all -Djavax.xml.accessExternalSchema=all -Djavax.xml.accessExternalDTD=file,http -Duser.home=$HOME -v"
export MAVEN_OPTS="-Duser.home=$HOME"

git clone https://github.com/scottmarlow/cditck-porting.git
cd cditck-porting
git checkout jms

wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
unzip apache-maven-3.6.3-bin.zip
export MAVEN_HOME=$PWD/apache-maven-3.6.3
export PATH=$MAVEN_HOME/bin:$PATH
echo using $MAVEN_HOME

export WORKSPACE=$PWD
wget https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip
mv glassfish-6.0.0-SNAPSHOT-nightly.zip latest-glassfish.zip

bash -x docker/build_cditck.sh 2>&1 | tee build.log
bash -x docker/run_cditck.sh 2>&1 | tee run.log

```

**Comment by scottmarlow** [comment]
Hmm, ^ is not working currently, must be a jvm issue.

**Comment by scottmarlow** [comment]
With the https://github.com/eclipse-ee4j/cditck-porting/pull/19 change, the only failure I see locally is ```testSecurityContextPropagation(org.jboss.cdi.tck.tests.event.observer.context.async.enterprise.EnterpriseSecurityContextPropagationInAsyncObserverTest)```

**Comment by scottmarlow** [comment]
From ./cdi-tck-report/cdi-3.0.0/TestSuite.txt:
```
Tests run: 1794, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,120.41 sec <<< FAILURE!
testSecurityContextPropagation(org.jboss.cdi.tck.tests.event.observer.context.async.enterprise.EnterpriseSecurityContextPropagationInAsyncObserverTest)  Time elapsed: 2.048 sec  <<< FAILURE!
java.lang.NullPointerException
        at org.jboss.cdi.tck.tests.event.observer.context.async.enterprise.EnterpriseSecurityContextPropagationInAsyncObserverTest.testSecurityContextPropagation(EnterpriseSecurityContextPropagationInAsyncObserverTest.java:59)
```

**Comment by scottmarlow** [comment]
From ./cdi-tck-glassfish-porting/glassfish-tck-runner/target/surefire-reports/testng-results.xml:
```
java.lang.NullPointerException
at org.jboss.cdi.tck.tests.event.observer.context.async.enterprise.EnterpriseSecurityContextPropagationInAsyncObserverTest.testSecurityContextPropagation(EnterpriseSecurityContextPropagationInAsyncObserverTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
at org.jboss.arquillian.testng.Arquillian$2.invoke(Arquillian.java:145)
at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
at org.jboss.arquillian.container.test.impl.execution.ContainerTestExecuter.execute(ContainerTestExecuter.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:139)
at org.jboss.arquillian.testng.Arquillian.run(Arquillian.java:138)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.jboss.arquillian.testng.container.TestNGTestRunner.execute(TestNGTestRunner.java:51)
at org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.executeTest(ServletTestRunner.java:139)
at org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
at org.jboss.arquillian.protocol.servlet5.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1540)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
at java.lang.Thread.run(Thread.java:748)
])
```

**Comment by gurunrao** [comment]
@scottmarlow @starksm64 thanks for fixs for jms failures, we now have only 1 failure.
CI run details - https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/71/testReport/

**Comment by smillidge** [comment]
That issue maybe related to the upgrade to the latest version of Weld. We fixed this in Payara last year with https://github.com/payara/Payara/pull/4210 to fix this TCK failure. That work may need back porting. @starksm64 does that make sense to the Weld team?

**Comment by starksm64** [comment]
@smillidge Yes, that type of integration should be required to propagate the security context. I'm testing that now and will create a PR if it clears up the test. The CDI api and Weld version should be updated as well so that is what I'm testing.

**Comment by starksm64** [comment]
The security context propagation PR:
https://github.com/eclipse-ee4j/glassfish/pull/23156

**Comment by smillidge** [comment]
Should be fixed by #23156

**Comment by scottmarlow** [comment]
@gurunrao please try to run again on Thursday or after GlassFish nightly build is complete so we have the https://github.com/eclipse-ee4j/glassfish/pull/23156 fix included in the test run.

**Comment by gurunrao** [comment]
Thanks @starksm64 @scottmarlow . CDI porting kit has all pass with latest run, CI run can be found here - https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/72/testReport/
