### ISSUE TITLE
Outstanding failures in jpa testsuite with glassfish 6 web profile.

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23182]
jpa testsuite tests fail with glassfish 6 web profile.

## Environment Details
* GlassFish Version (and build number):6 nightly build Web profile.
* JDK version:1.8
* OS:Linux
* Database:Derby

Run Log and glassfish logs can be downloaded from here - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/9/artifact/jpa-results.tar.gz
file  "/root/run_cts.log" inside archive has run details.
directory  "/root/vi/glassfish6/glassfish/domains/domain1/logs/" has glassfish server logs.

Run logs can also be viewed here - https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-grao/branches/master/runs/9/nodes/36/steps/46/log/?start=0

**Comment by gurunrao** [comment]
I will re-validate the test-suite with latest nightly build here - https://ci.eclipse.org/jakartaee-tck/job/build-glassfish/lastSuccessfulBuild/artifact/appserver/distributions/web/target/web.zip

**Comment by gurunrao** [comment]
completed re-validation results are here - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/9/testReport/

**Comment by scottmarlow** [comment]
@smillidge Regarding the ```database can not be found``` failure, are you going by the information in the job console output?  More specifically, the ```java.sql.SQLSyntaxErrorException: Schema 'CTS1' does not exist``` during ```configure.RI.backend```?  I'm just trying to sync with what is already understood.  Thanks!

@gurunrao I tried downloading https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/9/artifact/jpa-results.tar.gz but got ```file not found```.  I was going to look at the server.log file as the https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/9/consoleText output (downloaded as file, don't open in browser :) shows the below during the first test deployment:
```
   [runcts] OUT => [javatest.batch] Beginning Test:  com/sun/ts/tests/jpa/core/annotations/access/field/Client.java#fieldTypeTest1_from_pmservlet
   [runcts] OUT => [javatest.batch] ********************************************************************************
   [runcts] OUT => [javatest.batch] 
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - harness.executeMode is set to "0"
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - AutoDeployment.init()
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - AutoDeployment:  Using porting set #1
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Using porting.ts.deploy2.class.1
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - AutoDeployment.init()
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - AutoDeployment:  Using porting set #2
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Using porting.ts.deploy2.class.2
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - ss:  modified runtime.xml
   [runcts] OUT => [javatest.batch] Loading /root/jakartaeetck/bin/xml/../../src/com/sun/ts/lib/harness/commonarchives.properties
   [runcts] OUT => [javatest.batch] Loading /root/jakartaeetck/bin/xml/../../src/com/sun/ts/lib/harness/rebuildable.properties
   [runcts] OUT => [javatest.batch] Loading /root/jakartaeetck/bin/xml/../../src/vehicle.properties
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Undeploying apps...
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - AutoDeployment.isDeployed()
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - AutoDeployment.isDeployed()
   [runcts] OUT => [javatest.batch] Undeployed apps from - /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/core/annotations/access/field
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Search for s1as runtime files match:`jpa_core_annotations_access_field_pmservlet_vehicle_web.war`
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Valid runtime files after sweep:
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Search for s1as runtime files match:`jpa_core_annotations_access_field_puservlet_vehicle_web.war`
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Valid runtime files after sweep:
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Deploying apps for forward rebuildable...
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Search for s1as runtime files match:`jpa_core_annotations_access_field_pmservlet_vehicle_web.war`
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:18:  Harness - Valid runtime files after sweep:
   [runcts] OUT => [javatest.batch] 
   [runcts] OUT => [javatest.batch] -deploy:
   [runcts] OUT => [javatest.batch]   [gf.echo] Deploying:  /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/core/annotations/access/field/jpa_core_annotations_access_field_pmservlet_vehicle_web.war
   [runcts] OUT => [javatest.batch]   [gf.echo] 0 archive(s) to undeploy
   [runcts] OUT => [javatest.batch]   [gf.echo] Looking at /root/jakartaeetck/dist/com/sun/ts/tests/jpa/core/annotations/access/field/jpa_core_annotations_access_field_pmservlet_vehicle_web.war
   [runcts] OUT => [javatest.batch]   [gf.echo] Added sun xml file(s) to /root/jakartaeetck/dist/com/sun/ts/tests/jpa/core/annotations/access/field/jpa_core_annotations_access_field_pmservlet_vehicle_web.war
   [runcts] OUT => [javatest.batch]   [gf.echo] 1 archive(s) to deploy
   [runcts] OUT => [javatest.batch]      [copy] Copying 1 file to /root/vi/glassfish6/glassfish/domains/domain1/autodeploy
   [runcts] OUT => [javatest.batch]   [gf.echo] Deploying archive:  /root/jakartaeetck/dist/com/sun/ts/tests/jpa/core/annotations/access/field/jpa_core_annotations_access_field_pmservlet_vehicle_web.war
   [runcts] OUT => [javatest.batch]   [gf.echo] Deployment Failed:  jpa_core_annotations_access_field_pmservlet_vehicle_web.war
   [runcts] OUT => [javatest.batch] GF Deployment: Deployment failed for: /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/core/annotations/access/field/jpa_core_annotations_access_field_pmservlet_vehicle_web.war
   [runcts] OUT => [javatest.batch] /root/jakartaeetck/bin/xml/impl/glassfish/deploy.xml:53: The following error occurred while executing this line:
   [runcts] OUT => [javatest.batch] /root/jakartaeetck/bin/xml/impl/glassfish/deploy.xml:152: The following error occurred while executing this line:
   [runcts] OUT => [javatest.batch] /root/jakartaeetck/bin/xml/impl/glassfish/deploy.xml:212: Deployment Failed for one or more archives.  Check the server log to see which failed.
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Target.execute(Target.java:449)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.implementation.sun.javaee.glassfish.AutoDeployment.deploy(AutoDeployment.java:222)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.SuiteSynchronizer.continueToDeployApps(SuiteSynchronizer.java:1104)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.SuiteSynchronizer.deployApps(SuiteSynchronizer.java:716)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.SuiteSynchronizer.doDeployment(SuiteSynchronizer.java:387)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.TSHarnessObserver.startingTest(TSHarnessObserver.java:367)
   [runcts] OUT => [javatest.batch] 	at com.sun.javatest.Harness$Notifier.startingTest(Harness.java:995)
   [runcts] OUT => [javatest.batch] 	at com.sun.javatest.TestRunner.notifyStartingTest(TestRunner.java:212)
   [runcts] OUT => [javatest.batch] 	at com.sun.javatest.DefaultTestRunner.runTest(DefaultTestRunner.java:167)
   [runcts] OUT => [javatest.batch] 	at com.sun.javatest.DefaultTestRunner.access$100(DefaultTestRunner.java:43)
   [runcts] OUT => [javatest.batch] 	at com.sun.javatest.DefaultTestRunner$1.run(DefaultTestRunner.java:66)
   [runcts] OUT => [javatest.batch] Caused by: /root/jakartaeetck/bin/xml/impl/glassfish/deploy.xml:152: The following error occurred while executing this line:
   [runcts] OUT => [javatest.batch] /root/jakartaeetck/bin/xml/impl/glassfish/deploy.xml:212: Deployment Failed for one or more archives.  Check the server log to see which failed.
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:394)
   [runcts] OUT => [javatest.batch] 	at net.sf.antcontrib.logic.ForTask.doSequentialIteration(ForTask.java:259)
   [runcts] OUT => [javatest.batch] 	at net.sf.antcontrib.logic.ForTask.doToken(ForTask.java:268)
   [runcts] OUT => [javatest.batch] 	at net.sf.antcontrib.logic.ForTask.doTheTasks(ForTask.java:324)
   [runcts] OUT => [javatest.batch] 	at net.sf.antcontrib.logic.ForTask.execute(ForTask.java:244)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at java.util.Vector.forEach(Vector.java:1275)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [javatest.batch] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at java.util.Vector.forEach(Vector.java:1275)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
   [runcts] OUT => [javatest.batch] 	... 20 more
   [runcts] OUT => [javatest.batch] Caused by: /root/jakartaeetck/bin/xml/impl/glassfish/deploy.xml:212: Deployment Failed for one or more archives.  Check the server log to see which failed.
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.Exit.execute(Exit.java:162)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at java.util.Vector.forEach(Vector.java:1275)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [javatest.batch] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at java.util.Vector.forEach(Vector.java:1275)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.Task.perform(Task.java:350)
   [runcts] OUT => [javatest.batch] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
   [runcts] OUT => [javatest.batch] 	... 54 more
   [runcts] OUT => [javatest.batch] 08-18-2020 09:33:29:  Harness - Deployment of app(s) from:  /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/jpa/core/annotations/access/field failed!
```

**Comment by gurunrao** [comment]
@scottmarlow - the failures with glassfish 6 web profile  are mainly due to removal of webservices-osgi.jar from web-profile bundle.
I am working on the removal of webservices-osgi.jar package removal which is causing failures.

**Comment by smillidge** [comment]
@scottmarlow there's lots of errors like
 `Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: The connection was refused because the database derbyDB was not found.
7544:  Error Code: 0]]`
