### ISSUE TITLE
org.glassfish.admin.rest.resources.generatedASM.DomainResource

### ISSUE THREAD

**Issue by kronos72it** [eclipse-ee4j/glassfish#23219]
[//]: # "Provide a general summary of the issue in the Title above"

Error starting GF after bug fix [hibernate cdi validator bundle](https://github.com/eclipse-ee4j/glassfish/issues/22712)

## Environment Details
* GlassFish Version (and build number):
* JDK version: 8 for GF , 13 for NB(12)
* OS:win 7
* Database:

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
I got the error: java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [246], anyway admin console is online but I want to have a stable GF installation .
[//]: # "State if the problem is easily reproducible or happens intermittently"
Problem is non intermittend
[//]: # "Include stack traces or command outputs"

 `Authorization Service has successfully initialized.|#]
  Grizzly Framework 2.4.4 started in: 80ms - bound to [/0.0.0.0:8080]|#]
  Grizzly Framework 2.4.4 started in: 0ms - bound to [/0.0.0.0:8181]|#]
  Grizzly Framework 2.4.4 started in: 0ms - bound to [/0.0.0.0:4848]|#]
  Grizzly Framework 2.4.4 started in: 10ms - bound to [/0.0.0.0:3700]|#]
  GlassFish Server Open Source Edition  5.1.0  (default-private) startup time : Felix (3.600ms), startup services(1.100ms), total(4.700ms)|#]
  JTS5014: Recoverable JTS instance, serverId = [100]|#]
  Grizzly Framework 2.4.4 started in: 0ms - bound to [/0.0.0.0:7676]|#]
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://PO-SAVINO:8686/jndi/rmi://PO-SAVINO:8686/jmxrmi|#]
  HV000001: Hibernate Validator 6.0.10.Final|#]
  Grizzly Framework 2.4.4 started in: 0ms - bound to [/0.0.0.0:8080]|#]
  Grizzly Framework 2.4.4 started in: 2ms - bound to [/0.0.0.0:8181]|#]
  java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [246]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.glassfish.admin.rest.adapter.RestManagementResourceProvider.getResourceClasses(RestManagementResourceProvider.java:86)
	at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:270)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:151)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:439)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)`

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
I got the error:
 Exception while loading the app : java.lang.ClassNotFoundException: org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor
java.lang.ClassNotFoundException: org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor
        at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:841)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:718)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
then fixed the bean-validator-cdi as described in the Github issue
Starting again GF from NB and got the new one error : java.lang.ClassNotFoundException: org.glassfish.admin.rest.resources.generatedASM.DomainResource not found by org.glassfish.main.admin.rest-service [246]
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by gerdogdu** [comment]
Sorry but what are you trying to do?

**Comment by smillidge** [comment]
Closing due to no response. Reopen if this is an issue.

**Comment by DylanJo2002** [comment]
I have the same error. Do anyone know how to fix it?
