### ISSUE TITLE
JSONB TCK tests are now getting "jakarta.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found" failures with glassfish-6.0.0-SNAPSHOT-2020-09-20.zip

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/glassfish#23210]
We didn't see this failure with [GlassFish nightly build](https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip) from 2020-09-13 but we do now with the glassfish-6.0.0-SNAPSHOT-2020-09-20.zip weekly build.

Failure from https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1073/artifact/jsonb-results.tar.gz

```
jakarta.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found; nested exception is: 
   [runcts] OUT => [javatest.batch] 	java.util.ServiceConfigurationError: jakarta.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.javax.rmi.CORBA.Util.mapSystemException(Util.java:157)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:171)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:110)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:197)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.tests.common.vehicle.ejb._EJBVehicleHome_DynamicStub.create(com/sun/ts/tests/common/vehicle/ejb/_EJBVehicleHome_DynamicStub.java)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.tests.common.vehicle.ejb.EJBVehicleRunner.run(EJBVehicleRunner.java:66)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:38)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:422)
   [runcts] OUT => [javatest.batch] 	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:159)
   [runcts] OUT => [javatest.batch] 	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:41)
   [runcts] OUT => [javatest.batch] Caused by: java.rmi.RemoteException: jakarta.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found; nested exception is: 
   [runcts] OUT => [javatest.batch] 	java.util.ServiceConfigurationError: jakarta.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
   [runcts] OUT => [javatest.batch] 	at com.sun.ejb.containers.InvocationHandlerUtil.throwRemoteException(InvocationHandlerUtil.java:111)
   [runcts] OUT => [javatest.batch] 	at com.sun.ejb.containers.EJBHomeInvocationHandler.invoke(EJBHomeInvocationHandler.java:286)
   [runcts] OUT => [javatest.batch] 	at com.sun.proxy.$Proxy242.create(Unknown Source)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:113)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:143)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:492)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:163)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1520)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1396)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:901)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:183)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:665)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:467)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2193)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:467)
   [runcts] OUT => [javatest.batch] 	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:510)
   [runcts] OUT => [javatest.batch] Caused by: java.util.ServiceConfigurationError: jakarta.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
   [runcts] OUT => [javatest.batch] 	at java.security.AccessController.doPrivileged(Native Method)
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
   [runcts] OUT => [javatest.batch] 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
   [runcts] OUT => [javatest.batch] 	at jakarta.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:90)
   [runcts] OUT => [javatest.batch] 	at jakarta.json.bind.JsonbBuilder.create(JsonbBuilder.java:86)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.tests.jsonb.api.annotation.AnnotationTest.<init>(AnnotationTest.java:51)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   [runcts] OUT => [javatest.batch] 	at java.lang.Class.newInstance(Class.java:442)
   [runcts] OUT => [javatest.batch] 	at com.sun.ts.tests.common.vehicle.ejb.EJBVehicle.ejbCreate(EJBVehicle.java:55)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [runcts] OUT => [javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [runcts] OUT => [javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [runcts] OUT => [javatest.batch] 	at org.glassfish.ejb.security.application.EJBSecurityManager$5.run(EJBSecurityManager.java:1134)
   [runcts] OUT => [javatest.batch] 	at java.security.AccessController.doPrivileged(Native Method)
   [runcts] OUT => [javatest.batch] 	at org.glassfish.ejb.security.application.EJBSecurityManager.doAsPrivileged(EJBSecurityManager.java:1032)
   [runcts] OUT => [javatest.batch] 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1139)
   [runcts] OUT => [javatest.batch] 	at com.sun.ejb.containers.BaseContainer.invokeTargetBeanMethod(BaseContainer.java:4220)
   [runcts] OUT => [javatest.batch] 	at com.sun.ejb.containers.EJBHomeInvocationHandler.invokeTargetBeanMethod(EJBHomeInvocationHandler.java:318)
   [runcts] OUT => [javatest.batch] 	at com.sun.ejb.containers.EJBHomeInvocationHandler.invoke(EJBHomeInvocationHandler.java:250)
   [runcts] OUT => [javatest.batch] 	... 18 more
   [runcts] OUT => [javatest.batch] 
```

**Comment by smillidge** [comment]
@lukasj any ideas?

**Comment by scottmarlow** [comment]
From @jansupol on GlassFish dev ml:
```
Short answer is that JSON-P 2.0.0 has OSGi version moved from 1.2 to 2.0. Yasson OSGi manifest needs to react to it. Yasson team is working on it.
```

**Comment by smillidge** [comment]
@jansupol @m0mus any update on a new version of Yasson. I noticed Yasson has been through ballot is that an issue?

**Comment by edbratt** [comment]
So long as the API is unchanged and the implementation version used for 
the ballot remains available -- and the new version also passes the TCK, 
implementations can be modified without impacting the Spec. The version 
used for the GlassFish ballot should similarly be archived but there is 
no requirement they be one and the same.

**Comment by m0mus** [comment]
@smillidge new Yasson is coming soon. @Verdent is working on it.
