### ISSUE TITLE
...hk2.RequestContext must be in the Singleton scope

### ISSUE THREAD

**Issue by tigeleo** [eclipse-ee4j/glassfish#23319]
## Environment Details
* GlassFish Version (and build number):2.33
* JDK version:11.4
* OS:Linux
* Database:

----------

I update my jersey from 1.19 to 2.33. 
I need do it because when we update tomcat from 7 to 9 class loader start load jars in other random order. It cause application failed because jar  javax.ws.rs-api-2.0.1.jar that require Jersey 2. 
After adding and update many jars , I get exception: 
```
07-Jan-2021 19:52:24.057 SEVERE [http-nio-1701-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [Jersey Web Ap
plication]
        java.lang.IllegalArgumentException: The implementation class org.glassfish.jersey.inject.hk2.RequestContext must be in the Singleton scope
                at org.jvnet.hk2.internal.ServiceLocatorImpl.checkConfiguration(ServiceLocatorImpl.java:1729)
                at org.jvnet.hk2.internal.ServiceLocatorImpl.addConfiguration(ServiceLocatorImpl.java:2124)
                at org.jvnet.hk2.internal.DynamicConfigurationImpl.commit(DynamicConfigurationImpl.java:261)
                at org.glassfish.hk2.utilities.ServiceLocatorUtilities.bind(ServiceLocatorUtilities.java:167)
                at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.<init>(AbstractHk2InjectionManager.java:65)
                at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.<init>(ImmediateHk2InjectionManager.java:38)
                at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFac
tory.java:55)
                at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:73)
                at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:69)
                at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
                at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
                at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
                at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
                at javax.servlet.GenericServlet.init(GenericServlet.java:158)
                at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
                at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
                at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)


```

What it mean? Where I need implement RequestContext  in singletone scope?

**Comment by gerdogdu** [comment]
As I understand from your question, you are using Apache Tomcat not the Eclipse GlassFish server. If you have a specific question for Eclipse Jersey, you need to open an issue for Jersey or Tomcat.

**Comment by tigeleo** [comment]
Yes . I use tomcat 9.

**Comment by smillidge** [comment]
Closing as not a GlassFish issue,
