### ISSUE TITLE
Resource Validation NPE

### ISSUE THREAD

**Issue by kronos72it** [eclipse-ee4j/glassfish#23316]
## Environment Details
* GlassFish Version (and build number):6.0.0 
* JDK version: 11.02 for project , 1.8 for GF
* OS: Win 7
* Database: MySql 5
* Maven 3.6.3 on JDK 11.02
----------

## Problem Description
I am adopting Jakarta EE 9 and downloaded the GF 6 and NetBeans 12.0 . Modified all import and namespaces to be Jakarta EE 9 compliant .Debugging built EAR and got the below stack trace.
The problem is reproducible , for me with my project
`Exception while dispatching an event
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at com.sun.enterprise.deployment.util.ResourceValidator$JNDINamespace.storeAppScopedResources(ResourceValidator.java:978)
	at com.sun.enterprise.deployment.util.ResourceValidator$JNDINamespace.access$1400(ResourceValidator.java:949)
	at com.sun.enterprise.deployment.util.ResourceValidator$AppResources.storeAppScopedResources(ResourceValidator.java:941)
	at com.sun.enterprise.deployment.util.ResourceValidator$AppResources.access$100(ResourceValidator.java:913)
	at com.sun.enterprise.deployment.util.ResourceValidator.parseResources(ResourceValidator.java:139)
	at com.sun.enterprise.deployment.util.ResourceValidator.event(ResourceValidator.java:108)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:107)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:399)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:195)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:516)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:512)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:511)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:542)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:534)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:533)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1441)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:86)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1699)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:510)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:200)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:150)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.lang.Thread.run(Thread.java:748)`

## Steps to reproduce

1. build the project 
2. use the context menù inside NB to debug  
## Impact of Issue
I am tring to adopt Jakarta EE 9 and complete a personal application

[//]: # "Please choose one each Type, Component, and Priority label"
Enterprise Application , EJB WAR, normal

**Comment by gerdogdu** [comment]
It is impossible to solve your problem without more information. I appreciate if you provide sample code in Github to deploy.

**Comment by kronos72it** [comment]
not reproducible
