### ISSUE TITLE
Exception After Deploying ActiveMQ RAR File

### ISSUE THREAD

**Issue by gerdogdu** [eclipse-ee4j/glassfish#23320]
Hi folks
In GlassFish Version **5.1.1-SNAPSHOT** version, I deployed the ActiveMQ RAR file but after the deployment, it throws the following error:

Circular dependency during start of glassfish 5.1.1-SNAPSHOT with deployed and installed activemq-rar-5.16.0.rar
...
```
JTS5043: Unexpected error occurred while creating transaction manager instance MultiException stack 1 of 1 java.lang.IllegalStateException: Circular dependency involving org.glassfish.resourcebase.resources.listener.ResourceManager was found. Full descriptor is SystemDescriptor( implementation=org.glassfish.resourcebase.resources.listener.ResourceManager
....
....
```

I debugged the code, and it thorws the exception in **_appserver/transaction/jts/src/main/java/com/sun/jts/jta/TransactionServiceProperties.java #  public static void initRecovery(boolean force) {_** 

for this line:

`serviceLocator.getAllServices(BuilderHelper.createNameFilter("ResourceManager"));`

I commented out this code, and everything is working correctly.
Do you have any idea?
Regards.
Gurkan

**Comment by gerdogdu** [comment]
Here is the exact exception:

`[2021-01-17T19:33:09.209+0300] [glassfish 5.1] [SEVERE] [jts.unexpected_error_in_create_transaction_manager] [javax.enterprise.system.core.transaction.com.sun.jts.jta] [tid: _ThreadID=43 _ThreadName=RunLevelControllerThread-1610901188873] [timeMillis: 1610901189209] [levelValue: 1000] [[
  JTS5043: Unexpected error occurred while creating transaction manager instance
MultiException stack 1 of 1
java.lang.IllegalStateException: Circular dependency involving org.glassfish.resourcebase.resources.listener.ResourceManager was found.  Full descriptor is SystemDescriptor(
	implementation=org.glassfish.resourcebase.resources.listener.ResourceManager
	name=ResourceManager
	contracts={org.glassfish.resourcebase.resources.listener.ResourceManager,org.jvnet.hk2.config.ConfigListener}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={2},runLevelMode={0},Bundle-SymbolicName={org.glassfish.main.resourcebase.resources.nucleus-resources},Bundle-Version={5.1.1.SNAPSHOT}
	rank=0
	loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [org.glassfish.main.resourcebase.resources.nucleus-resources [288]], State = [READY],1650625974)
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=805
	locatorId=0
	identityHashCode=1379321593
	reified=true)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:204)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:92)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:66)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServiceLocatorImpl.java:837)
	at com.sun.jts.jta.TransactionServiceProperties.initRecovery(TransactionServiceProperties.java:294)
	at com.sun.jts.jta.TransactionManagerImpl.<init>(TransactionManagerImpl.java:185)
	at com.sun.jts.jta.TransactionManagerImpl.getTransactionManagerImpl(TransactionManagerImpl.java:153)
	at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.postConstruct(JavaEETransactionManagerJTSDelegate.java:121)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1468)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServiceLocatorImpl.java:795)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServiceLocatorImpl.java:783)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.initDelegates(JavaEETransactionManagerSimplified.java:1480)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.postConstruct(JavaEETransactionManagerSimplified.java:141)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:92)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:675)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:662)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:754)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:766)
	at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:87)
	at com.sun.enterprise.resource.deployer.ResourceAdapterConfigDeployer.getConnectorRuntime(ResourceAdapterConfigDeployer.java:75)
	at com.sun.enterprise.resource.deployer.ResourceAdapterConfigDeployer.deployResource(ResourceAdapterConfigDeployer.java:62)
	at org.glassfish.resourcebase.resources.listener.ResourceManager.deployResources(ResourceManager.java:159)
	at org.glassfish.resourcebase.resources.listener.ResourceManager.postConstruct(ResourceManager.java:105)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:92)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:66)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]`

**Comment by gerdogdu** [comment]
As stated here, #https://github.com/eclipse-ee4j/glassfish/issues/23315 removal of TransactionManager early creation also fixes the issue. 

Can we commit updated code which remove the below line from JavaEETransactionManagerJTSDelegate#postConstruct?
`transactionManagerImpl = TransactionManagerImpl.getTransactionManagerImpl();`
