### ISSUE TITLE
Fix "java.lang.Exception: Manifest error: Missing attribute name -  sun.security.action,sun.security.internal.spec,sun.security.jgss" during boot

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23351]
When starting up a GF build from the current master, an exception is logged:

```
WARNING: Failed to install file:/glassfish6/glassfish/modules/glassfish-extra-jre-packages.jar.
org.osgi.framework.BundleException: Could not create bundle object.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3312)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
	at com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.install(BundleProvisioner.java:420)
	at com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.installBundles(BundleProvisioner.java:180)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:118)
	at org.glassfish.embeddable.GlassFishRuntime._bootstrap(GlassFishRuntime.java:133)
	at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:86)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:73)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:30)
Caused by: java.lang.Exception: Manifest error: Missing attribute name -  sun.security.action,sun.security.internal.spec,sun.security.jgss,
	at org.apache.felix.framework.cache.BundleCache.getMainAttributes(BundleCache.java:352)
	at org.apache.felix.framework.cache.BundleCache.getMainAttributes(BundleCache.java:199)
	at org.apache.felix.framework.cache.JarRevision.getManifestHeader(JarRevision.java:103)
	at org.apache.felix.framework.util.Util.getMultiReleaseAwareManifestHeaders(Util.java:993)
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1266)
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:113)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3260)
```

This exception should be investigated and fixed.

**Comment by arjantijms** [comment]
The error is caused by some formatting of the jar plugin, destroying the manifest format.

However, a bigger question is whether the `glassfish-extra-jre-packages` should even be required for JDK 11. Most likely not.
