### ISSUE TITLE
JAXB Exception when starting admin console

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23361]
When starting the admin console on GlassFish 6 (current master) the following exception is logged:

```
[#|2021-02-13T15:37:14.911+0100|WARNING|glassfish 6.0|org.glassfish.grizzly.http.server.HttpHandler|_ThreadID=79;_ThreadName=admin-listener(3);_TimeMillis=1613227034911;_LevelValue=900;|
  GRIZZLY0203: Unexpected error

java.lang.ClassNotFoundException: jakarta.xml.bind.JAXBContext not found by [238]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
java.lang.NoClassDefFoundError: jakarta/xml/bind/JAXBContext
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2344)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2162)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2096)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:168)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:313)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:478)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:435)
	at org.glassfish.jersey.server.wadl.internal.WadlApplicationContextImpl.getJAXBContextFromWadlGenerator(WadlApplicationContextImpl.java:120)
	at org.glassfish.jersey.server.wadl.WadlFeature.isJaxB(WadlFeature.java:74)
	at org.glassfish.jersey.server.wadl.WadlFeature.configure(WadlFeature.java:56)
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:728)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:647)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:246)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:310)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainerProvider.createContainer(GrizzlyHttpContainerProvider.java:37)
	at org.glassfish.jersey.server.ContainerFactory.createContainer(ContainerFactory.java:58)
	at org.glassfish.admin.rest.adapter.RestAdapter.getJerseyContainer(RestAdapter.java:288)
	at org.glassfish.admin.rest.adapter.RestAdapter.exposeContext(RestAdapter.java:281)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:151)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

The admin console subsequently doesn't run.

**Comment by arjantijms** [comment]
There's a big and somewhat nasty story in the comments of `org.glassfish.hk2.osgiresourcelocator.ServiceLoader` about what the code is doing:

```
    /**
     * It is not clear why one needs this method, but it is provided just in case one needs it.
     * 
     * Returns classes found in META-INF/services/serviceClass.getName() in OSGi bundles. This method searches for
     * such named resources in every OSGi bundle. For every resource found, it assumes that the file contains
     * a class name. It loads the class name mentioned in that file using the bundle containing the resource.
     * It does not check if the class mentioned in provider file actually implements/extends service class,
     * because there are cases where it does not. 
     * 
     * JAXB is an example. 
     * 
     * JAXBContext provider file contains a class that's used as a factory class for JAXBContext. 
     * To handle such issues, yet not return classes that are not class loader compatible, this method will only 
     * return those classes which see the same service class as supplied in the parameter.
     * 
     * Let's take an example. 
     * 
     * We have JAXB classes exported by JRE and there is a bundle A which contains JAXB API
     * and implementation. The bundle B is wired to itself for JAXB classes. Assume a user supplied bundle
     * B is wired to JRE's JAXB. 
     * 
     * When bundle B calls JAXBContext.createContext(JAXBContext.class),
     * JRE's JAXBContext will use this API. The implementation will look for META-INF/services/JAXBContext files and
     * find a file in JAXB bundle. Let's say that file contains com.acme.jaxb.JAXBContextFactory.
     * com.acme.jaxb.ContextFactory does not implement JAXBContext.class. Instead, as per JAXB spec,
     * it must provide some factory methods to create JAXBContext. 
     * 
     * If our implementation simply returns that class without doing any further tests, a nasty class cast exception 
     * is going to be resulted, because user's bundle B uses JAXB from JRE, which means JAXBContext.class is loaded 
     * by JRE, yet com.acme.jaxb.JAXBContextFactory uses JAXBContext from bundle A. 
     * 
     * To avoid such problem, we will try to load JAXBContext using class loader of
     * com.acme.jaxb.JAXBContextFactory and see if that's same as supplied JAXBContext.class. If they are same,
     * we return com.acme.jaxb.JAXBContextFactory, else we don't. In this example, we won't.
     *
     * @param serviceClass type of service requested
     * @param <T>
     * @return classes corresponding to entries in META-INF/services file for the service class.
     */
    public static <T> Iterable<Class> lookupProviderClasses(Class<T> serviceClass) {
        return _me.lookupProviderClasses1(serviceClass);
    ```

**Comment by smillidge** [comment]
This is back in master any ideas?

**Comment by arjantijms** [comment]
@smillidge This PR should fix it: https://github.com/eclipse-ee4j/glassfish/pull/23393

**Comment by smillidge** [comment]
Yeah fixes it for me as well
