### ISSUE TITLE
Failed to deploy webservice

### ISSUE THREAD

**Issue by hussainnm** [eclipse-ee4j/glassfish#23373]
webservices-rt.jar is a multi-release jar and contains a version of XmlCatalogUtil that uses `javax.xml.catalog.CatalogManager` instead of `com.sun.org.apache.xml.internal.resolver.CatalogManager` but glassfish still throws a ClassNotFoundException.

Steps to reproduce:
Run Quick Look Test: `appserver/tests/quicklook/wsit/JaxwsFromWsdl`

Exception:
```
[#|2021-02-16T19:59:37.889+0530|WARNING|glassfish 6.1|jakarta.enterprise.webservices|_ThreadID=30;_ThreadName=RunLevelControllerThread-1613485573979;_TimeMillis=1613485777889;_LevelValue=900;_MessageID=AS-WSJSR109IMPL-00082;|
  Deployment failed
java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
        at com.sun.xml.ws.util.xml.XmlUtil.createEntityResolver(XmlUtil.java:287)
        at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:611)
        at org.glassfish.webservices.WSServletContextListener.registerEndpoint(WSServletContextListener.java:253)
        at org.glassfish.webservices.WSServletContextListener.contextInitialized(WSServletContextListener.java:94)
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5005)
        at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:559)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5574)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:507)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:877)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:860)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:644)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2020)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1666)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:83)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:98)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:267)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:328)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:476)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:195)
        at org.glassfish.webservices.metroglue.MetroContainer.deployWsTxServices(MetroContainer.java:206)
        at org.glassfish.webservices.metroglue.MetroContainer.deployWsTxServices(MetroContainer.java:154)
        at org.glassfish.webservices.metroglue.MetroContainer.onDeployed(MetroContainer.java:139)
        at org.glassfish.webservices.WebServiceDeploymentNotifierImpl.notifyDeployed(WebServiceDeploymentNotifierImpl.java:42)
        at org.glassfish.webservices.deployment.WebServicesDeploymentMBean.deploy(WebServicesDeploymentMBean.java:278)
        at org.glassfish.webservices.WebServicesDeployer.prepare(WebServicesDeployer.java:172)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:901)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:410)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:382)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:219)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2103)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1212)
        at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1606)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1522)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 42 more
|#]

[#|2021-02-16T19:59:37.889+0530|SEVERE|glassfish 6.1|jakarta.enterprise.web.core|_ThreadID=30;_ThreadName=RunLevelControllerThread-1613485573979;_TimeMillis=1613485777889;_LevelValue=1000;_MessageID=AS-WEB-CORE-00174;|
  Startup of context /__wstx-services failed due to previous errors|#]
```

**Comment by hussainnm** [comment]
Looks like we need webservices-osgi.jar with multi-release support. See https://github.com/eclipse-ee4j/metro-wsit/issues/54

As mentioned in the issue, adding [resolver.jar](https://search.maven.org/artifact/com.sun.org.apache.xml.internal/resolver/20050927/jar) to lib solves the ClassNotFoundException.

**Comment by lukasj** [comment]
glassfish should _never_ use `webservices-rt`/`webservices-tools`, they are not OSGi bundles. What GlassFish needs is `webservices-osgi.jar` (and  `webservices-extra-jdk-packages` eventually).
