### ISSUE TITLE
Some tests using Ant trigger Permissions.setSecurityManager, which fails on JDK 18

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23721]
Executing `./gftest.sh cdi_all` on GlassFish 6.2.3 using JDK 18 (build 18-ea+24-1608) causes the following exception to be thrown:

``` 
    [java] java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
     [java] 	at java.base/java.lang.System.setSecurityManager(System.java:411)
     [java] 	at org.apache.tools.ant.types.Permissions.setSecurityManager(Permissions.java:103)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:216)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:194)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:891)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [java] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [java] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [java] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [java] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [java] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [java] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [java] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [java] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [java] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
     [java] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
     [java] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
     [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:818)
     [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
     [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
     [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

**Comment by arjantijms** [comment]
See https://bz.apache.org/bugzilla/show_bug.cgi?id=65345

**Comment by arjantijms** [comment]
The way to allow Derby to run on JDK 18 is disabling its internal usage of the security manager by adding "-noSecurityManager" as a startup flag.

**Comment by arjantijms** [comment]
The way to allow Derby to run on JDK 18 is disabling its internal usage of the security manager by adding "-noSecurityManager" as a startup flag.
