### ISSUE TITLE
Load Defaults button in JDBC Connection Pool throws IllegalStateException

### ISSUE THREAD

**Issue by ttelang** [eclipse-ee4j/glassfish#23771]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 6.2.3
* JDK version: 17
* OS: MacOS Big Sur
* Database: Apache Derby

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

Load Defaults button of the "Edit JDBC Connection Pool Page" throws the following exception

```
HTTP Status 500 - Internal Server Error
type Exception report
messageInternal Server Error
descriptionThe server encountered an internal error that prevented it from fulfilling this request.
exception
java.lang.IllegalStateException: getOutputStream() has already been called for this response
note The full stack traces of the exception and its root causes are available in the Eclipse GlassFish 6.2.3 logs.
````
Eclipse GlassFish 6.2.3
[//]: # "State if the problem is easily reproducible or happens intermittently"
intermittently

[//]: # "Include stack traces or command outputs"
```
[2022-01-26T20:37:57.342+0530] [glassfish 6.2] [WARNING] [] [jakarta.enterprise.web] [tid: _ThreadID=56 _ThreadName=admin-listener(4)] [timeMillis: 1643209677342] [levelValue: 900] [[
  StandardWrapperValve[FacesServlet]: Servlet.service() for servlet FacesServlet threw exception
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:695)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:180)
	at com.sun.faces.context.ExternalContextImpl.getResponseOutputWriter(ExternalContextImpl.java:817)
	at com.sun.faces.context.PartialViewContextImpl.createPartialResponseWriter(PartialViewContextImpl.java:512)
	at com.sun.faces.context.PartialViewContextImpl.access$300(PartialViewContextImpl.java:64)
	at com.sun.faces.context.PartialViewContextImpl$DelayedInitPartialResponseWriter.getWrapped(PartialViewContextImpl.java:635)
	at jakarta.faces.context.PartialResponseWriter.startDocument(PartialResponseWriter.java:97)
	at com.sun.faces.context.AjaxExceptionHandlerImpl.handlePartialResponseError(AjaxExceptionHandlerImpl.java:164)
	at com.sun.faces.context.AjaxExceptionHandlerImpl.handle(AjaxExceptionHandlerImpl.java:94)
	at jakarta.faces.context.ExceptionHandlerWrapper.handle(ExceptionHandlerWrapper.java:94)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:88)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:682)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:437)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1540)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at com.sun.webui.jsf.util.UploadFilter.doFilter(UploadFilter.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:215)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:555)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:73)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:114)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:199)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```
## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
1. Go to Admin Console -> http://localhost:4848
2. Create a new JDBC Connection Pool.
3. Open on an existing JDBC Connection Pool and go to Edit JDBC Connection Pool Page.
4. Click the Load Defaults button.

[//]: # "Provide sample code/application if relevant"
NA
## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
Unable to update a JDBC Connection Pool and the Admin Console crashes.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by pzygielo** [comment]
Seems to work fine now, with 7.0.0-M10, openjdk-17.0.5

**Comment by dmatej** [comment]
I have checked now that it works well on 7.0.9 too.
