### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by asimonsy** [eclipse-ee4j/glassfish#23805]
## Environment Details
* GlassFish Version: 6.2.5
* JDK version: 17.0.1

----------

## Problem Description

This is the stack trace I get when I try to run my application compiled in JDK 17:

```
Exception in thread "main" java.lang.Error: Could not initialize access to ClassLoader.defineClass method.
	at com.sun.ejb.codegen.ClassGenerator.<clinit>(ClassGenerator.java:60)
	at com.sun.ejb.codegen.Generator.generate(Generator.java:140)
	at com.sun.ejb.codegen.EjbClassGeneratorFactory.generate(EjbClassGeneratorFactory.java:116)
	at com.sun.ejb.codegen.EjbClassGeneratorFactory.ensureGenericHome(EjbClassGeneratorFactory.java:59)
	at com.sun.ejb.EJBUtils.loadGeneratedGenericEJBHomeClass(EJBUtils.java:384)
	at com.sun.ejb.EJBUtils.lookupRemote30BusinessObject(EJBUtils.java:323)
	at com.sun.ejb.containers.RemoteBusinessObjectFactory.getObjectInstance(RemoteBusinessObjectFactory.java:40)
	at java.naming/javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:342)
	at com.sun.enterprise.naming.impl.SerialContext.getObjectInstance(SerialContext.java:503)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:463)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:414)
	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.sun.ejb.codegen.ClassGenerator.lambda$static$0(ClassGenerator.java:51)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at com.sun.ejb.codegen.ClassGenerator.<clinit>(ClassGenerator.java:57)
	... 14 more
```

If I compile and run the same in JDK 11 there are just some warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.ejb.codegen.ClassGenerator to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.ejb.codegen.ClassGenerator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by arjantijms** [comment]
Thanks for the report, we'll be sure to look at this.

As always, a reproducer will very likely help us a lot here.

**Comment by dmatej** [comment]
And that's because I was lazy to run all tests on JDK17 again! :)
Thanks for the report, you were fast!

**Comment by dmatej** [comment]
Btw how do you call the client?
You should use this JVM option `--add-opens=java.base/java.lang=ALL-UNNAMED`
I will try to run tests with JDK17 for sure today.

**Comment by dmatej** [comment]
I tried to rerun all tests with JDK17 and they passed, so I expect that you just really need to add the `--add-opens` option and it should work.

**Comment by scottmarlow** [comment]
We are seeing [java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @10315254](https://gist.github.com/scottmarlow/cafb1c9b63b4f56b6ddbfb5d6369b41b) with the nightly GlassFish 7 build with [Jakarta EE 10 Platform TCK testing](https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/38/).

Is it expected that GlassFish 7 will be updated to use the `--add-opens` solution?
