### ISSUE TITLE
Security TCK test failure with Glassfish7 M5

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/glassfish#23959]
## Environment Details
* GlassFish Version - 7.0.0- M5 (Full profile and web profile)
* JDK version: JDK11

----------

## Problem Description
3 Test failures in Security TCK(https://download.eclipse.org/es/jakartaee10/staged/eftl/jakarta-security-tck-3.0.0.zip) when run against Glassfish 7.0.0-M5 : 

Problem is easily reproducible 

1. ee.jakarta.tck.security.test.OpenIdDefaultIT.testOpenIdConnect 

Source of test : https://github.com/jakartaee/security/blob/master/tck/app-openid/src/test/java/ee/jakarta/tck/security/test/OpenIdDefaultIT.java 

Exception
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.997 s <<< FAILURE! - in ee.jakarta.tck.security.test.OpenIdDefaultIT
[ERROR] ee.jakarta.tck.security.test.OpenIdDefaultIT.testOpenIdConnect  Time elapsed: 1.738 s  <<< ERROR!
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500 Internal Server Error for http://localhost:8080/openid-client166397622136750874/Secured
	at ee.jakarta.tck.security.test.OpenIdDefaultIT.testOpenIdConnect(OpenIdDefaultIT.java:69)
```

2. ee.jakarta.tck.security.test.OpenIdWithELIT.testOpenIdConnect

Source of test : https://github.com/jakartaee/security/blob/master/tck/app-openid/src/test/java/ee/jakarta/tck/security/test/OpenIdWithELIT.java 

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.143 s <<< FAILURE! - in ee.jakarta.tck.security.test.OpenIdWithELIT
[ERROR] ee.jakarta.tck.security.test.OpenIdWithELIT.testOpenIdConnect  Time elapsed: 0.196 s  <<< ERROR!
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500 Internal Server Error for http://localhost:8080/openid-client6422900697888077568/Secured
	at ee.jakarta.tck.security.test.OpenIdWithELIT.testOpenIdConnect(OpenIdWithELIT.java:65)
```

3. ee.jakarta.tck.security.test.InvalidRedirectURIIT.testOpenIdConnect

Source of test : https://github.com/jakartaee/security/blob/master/tck/app-openid/src/test/java/ee/jakarta/tck/security/test/InvalidRedirectURIIT.java 

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.901 s <<< FAILURE! - in ee.jakarta.tck.security.test.InvalidRedirectURIIT
[ERROR] ee.jakarta.tck.security.test.InvalidRedirectURIIT.testOpenIdConnect  Time elapsed: 0.193 s  <<< FAILURE!
java.lang.AssertionError: expected:<404> but was:<500>
	at ee.jakarta.tck.security.test.InvalidRedirectURIIT.testOpenIdConnect(InvalidRedirectURIIT.java:85)
```

## Steps to reproduce

1. wget -q https://download.eclipse.org/es/jakartaee10/staged/eftl/jakarta-security-tck-3.0.0.zip
2. unzip jakarta-security-tck-3.0.0.zip ; cd security-tck-3.0.0/tck
3. mvn clean install -Pstaging,glassfish-ci-managed -Dglassfish.version=7.0.0-M5 surefire-report:failsafe-report-only -Daggregate=true  | tee /run.log

## Impact of Issue

Affects the successful completion of https://github.com/eclipse-ee4j/glassfish/issues/23950

**Comment by arjantijms** [comment]
This one has been fixed a couple of days ago and it should work again in the latest nightly.l
