### ISSUE TITLE
Debugging TCK failure with Glassfish 7

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23962]
Debugging TCK fails with Glassfish 7 with following error:

```
+ /opt/jdk-11.0.2/bin/java VerifySMAP /home/jenkins/agent/workspace/t-for-other-languages-tck_master/vi/glassfish7/glassfish/domains/domain1/generated/jsp/testclient/org/apache/jsp/Hello_jsp.class.smap
/home/jenkins/agent/workspace/t-for-other-languages-tck_master/vi/glassfish7/glassfish/domains/domain1/generated/jsp/testclient/org/apache/jsp/Hello_jsp.class.smap: Configuration error - File does not exists
Exception in thread "main" java.lang.RuntimeException: File does not exists
	at VerifySMAP.configError(Unknown Source)
	at VerifySMAP.readWhole(Unknown Source)
	at VerifySMAP.main(Unknown Source)
```

CI run link - https://ci.eclipse.org/jakartaee-tck/job/debugging-support-for-other-languages-tck/job/master/316/console

Following readme can be used to reproduce the test failure: https://github.com/eclipse-ee4j/debugging-support-for-other-languages-tck/blob/master/README.md

PS: same deubugging  TCK bundle  passes with GF 6.2.5

**Comment by gurunrao** [comment]
Fix will be implemented at debugging TCK.
