### ISSUE TITLE
EE 10 Web Profile Signature Test failure due to GlassFish 7 appclient container including an older Jakarta Annotation Managed Bean class from December 2021

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/glassfish#24014]
As per https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/lastCompletedBuild/testReport/com.sun.ts.tests.signaturetest.javaee/JavaEESigTest/signatureTest_from_appclient/ Signature (hard to read) test failure, the `jakarta.annotation` classes as observed a deployment application classpath, the contained jakarta.annotation is incorrect:
```
06-20-2022 11:34:31:  ********** Package 'jakarta.annotation' - PASSED (STATIC MODE) **********
06-20-2022 11:34:31:  


06-20-2022 11:34:31:  ********** VALIDATE IN REFLECTIVE MODE  ****
06-20-2022 11:34:31:  Reflective mode supports verification within containers (ie ejb, servlet, etc)
06-20-2022 11:34:31:  ERROR: Unexpected exception null
06-20-2022 11:34:31:  ERROR: Test case throws exception: signatureTest failed with an unexpected exception
06-20-2022 11:34:31:  ERROR: Exception at:  
06-20-2022 11:34:31:  ERROR: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.ts.tests.signaturetest.SigTestDriver.runSignatureTest(SigTestDriver.java:180)
	at com.sun.ts.tests.signaturetest.SignatureTestDriver.executeSigTest(SignatureTestDriver.java:213)
	at com.sun.ts.tests.signaturetest.SigTestEE.signatureTest(SigTestEE.java:277)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:41)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.appclient.client.acc.AppClientContainer.launch(AppClientContainer.java:420)
	at org.glassfish.appclient.client.AppClientFacade.launch(AppClientFacade.java:146)
	at org.glassfish.appclient.client.AppClientGroupFacade.main(AppClientGroupFacade.java:39)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at com.sun.tdk.signaturetest.SignatureTest.checkAnnotations(SignatureTest.java:1449)
	at com.sun.tdk.signaturetest.SignatureTest.checkClassDescription(SignatureTest.java:1265)
	at com.sun.tdk.signaturetest.SignatureTest.verifyClass(SignatureTest.java:1196)
	at com.sun.tdk.signaturetest.SignatureTest.verifyClass(SignatureTest.java:1058)
	at com.sun.tdk.signaturetest.SignatureTest.check(SignatureTest.java:821)
	at com.sun.tdk.signaturetest.SignatureTest.run(SignatureTest.java:293)
	... 25 more

06-20-2022 11:34:31:  $$$ SigTestEE.cleanup() called
06-20-2022 11:34:31:  cleanup
06-20-2022 11:34:31:  $$$ SigTestEE.cleanup() returning
STATUS:Failed.Test case throws exception: signatureTest failed with an unexpected exception
result: Failed. Test case throws exception: signatureTest failed with an unexpected exception


test result: Failed. Test case throws exception: signatureTest failed with an unexpected exception
```

The older ManagedBean class definition is coming from the glassfish/lib/appclient/weld-se-shaded.jar but GlassFish 7 appclient container should really depend on the (updated) glassfish/modules/jakarta.annotation-api.jar instead.

**Comment by scottmarlow** [comment]
https://github.com/weld/api/releases/tag/5.0.SP2 was released with the https://github.com/weld/api/pull/168 change to use the correct Jakarta Annotation (with deprecated ManagedBean class).
