### ISSUE TITLE
Application deployment failed: Exception while deploying the app [__admingui]

### ISSUE THREAD

**Issue by Serj-C** [eclipse-ee4j/glassfish#24126]
## Environment Details
* GlassFish Version (and build number): 7.0.0-M8, M9
* JDK version: OpenJDK 19
* OS: Windows 11
* Database: N/A (GlassFish Default DB)

----------

## Problem Description
Today I tried to install and run GlassFish 7.0.0-M9 but unfortunately ran into a problem (same happened with M8 build).
Issue appears when accessing the admin console: https://localhost:4848 after starting domain1 with command:

asadmin.bat start-domain --verbose

Admin Console loads forever with following status: "Status: The Admin Console application is loaded.".
If page is refreshed, it becomes blank.

Logged stack trace in terminal:
[#|2022-10-05T21:54:12.915167+03:00|SEVERE|GlassFish 7.0|jakarta.enterprise.system.core|_ThreadID=170;_ThreadName=Thread-23;_LevelValue=1000;|
  Exception while deploying the app [__admingui]|#]

[#|2022-10-05T21:54:12.916167+03:00|SEVERE|GlassFish 7.0|jakarta.enterprise.system.core|_ThreadID=170;_ThreadName=Thread-23;_LevelValue=1000;_MessageID=NCLS-CORE-00026;|
  Exception during lifecycle processing
com.sun.enterprise.module.ResolveError: Not able to locate a unique module by name org.glassfish.jakarta.el
        at com.sun.enterprise.v3.server.ClassLoaderHierarchyImpl.createApplicationParentCL(ClassLoaderHierarchyImpl.java:149)
        at org.glassfish.deployment.common.DeploymentContextImpl.createClassLoader(DeploymentContextImpl.java:229)
        at org.glassfish.deployment.common.DeploymentContextImpl.createDeploymentClassLoader(DeploymentContextImpl.java:213)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:401)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:382)
        at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:188)
        at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:77)
|#]

[#|2022-10-05T21:54:12.921166+03:00|SEVERE|GlassFish 7.0|jakarta.enterprise.system.core|_ThreadID=170;_ThreadName=Thread-23;_LevelValue=1000;_MessageID=NCLS-CORE-00041;|
  Application deployment failed: Exception while deploying the app [__admingui]|#]

## Steps to reproduce
1. Start domain1 with: asadmin.bat start-domain --verbose
2. Access Admin Console in the browser: https://localhost:4848

## Impact of Issue
Couldn't load the admin console and use the GUI features.

<img width="870" alt="terminal" src="https://user-images.githubusercontent.com/45560711/194142815-995a247a-e026-4a06-b760-aaae73fcdd3f.png">
<img width="1277" alt="adminConsole" src="https://user-images.githubusercontent.com/45560711/194142838-8c268301-b791-429f-9485-e3ce448cdbf4.png">

**Comment by dmatej** [comment]
Hi, we know about this, see https://github.com/eclipse-ee4j/glassfish/issues/23782
Fixing admin UI is still on the todo list, unfortunatellty.
