### ISSUE TITLE
CompletionStage return type in Rest

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24121]
## Environment Details
* GlassFish Version (and build number): 7.0.0-M9
* JDK version: 17
* OS: Windows 64
* Database: built-in Derby

I have request to support `CompletionStage` in REST, see https://github.com/eclipse-ee4j/jersey/issues/5103

But it still does not work in the latest Glassfish 7.0.0-M9.

Given the following resources.

```java
@Path("todos")
@RequestScoped
public class TodoResources {

    private static final Logger LOGGER = Logger.getLogger(TodoResources.class.getName());

    @Context
    ResourceContext resourceContext;

    @Context
    UriInfo uriInfo;

    @Inject
    TodoService todoService;

    @GET
    public CompletableFuture<Response> getAllTodos() {
        return todoService.getAllTodosAsync().thenApply(todos -> Response.ok(todos).build());
    }

    @POST
    public CompletionStage<Response> createTodo(Todo todo) throws Exception {
        return todoService.createAsync(todo)
                .thenApply(saved ->
                        Response.created(uriInfo.getBaseUriBuilder().path("todos/{id}").build(saved.getId())).build()
                );
    }
}
```

When running an Arquillian test [TodoResourceTest](https://github.com/hantsy/jakartaee10-sandbox/blob/master/concurrency/src/test/java/com/example/it/TodoResourceTest.java) to verify it, failed.

There is exceptions in the console.

```bash 
ERROR] com.example.it.TodoResourceTest.testCreateTodo  Time elapsed: 0.525 s  <<< ERROR!
java.util.concurrent.CompletionException: org.opentest4j.AssertionFailedError: expected: <201> but was: <500>
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.glassfish.jersey.client.JerseyInvocation$InvocationResponseCallback.completed(JerseyInvocation.java:1029)
        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
        at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
        at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
        at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:278)
        at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$6(ClientRuntime.java:182)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
        at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$7(ClientRuntime.java:156)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.opentest4j.AssertionFailedError: expected: <201> but was: <500>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at com.example.it.TodoResourceTest.lambda$testCreateTodo$1(TodoResourceTest.java:115)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        ... 27 more
```

The complete server log when running the tests: 
[server.log](https://github.com/eclipse-ee4j/glassfish/files/9689375/server.log)

**Comment by jansupol** [comment]
I do not know what `todoService.getAllTodosAsync()` looks like,
but the following (a bit artificial code to follow you example) 
```
    @GET
    public CompletionStage<Response> getAllTodos() {
        var todos = todoService.findAll();
        return CompletableFuture.supplyAsync(() -> todos).thenApply(ts -> Response.ok(ts).build());
    }
```
works well.

**Comment by hantsy** [comment]
@jansupol Do you used GF7 M9 without updating the jersey jars?

**Comment by jansupol** [comment]
The exception cause you report is >java.lang.IllegalStateException: Not inside a request scope.

It is caused by the CompletableFuture, which runs `uriInfo.getBaseUriBuilder()` in its own thread. But the thread is not aware of the ThreadLocal RequestScopes, so the scope is not found. I do not think we may be able to fix this on our side.  The change can be done on the app level:
```
    @POST
    public CompletionStage<Response> createTodo(Todo todo) throws Exception {
        UriBuilder builder = uriInfo.getBaseUriBuilder();
        return todoService.createAsync(todo)
                .thenApply(saved ->
                        Response.created(builder.path("todos/{id}").build(saved.getId())).build()
                );
    }
```
works well.

**Comment by hantsy** [comment]
> I do not know what `todoService.getAllTodosAsync()` looks like, but the following (a bit artificial code to follow your example)
> 
> ```
>     @GET
>     public CompletionStage<Response> getAllTodos() {
>         var todos = todoService.findAll();
>         return CompletableFuture.supplyAsync(() -> todos).thenApply(ts -> Response.ok(ts).build());
>     }
> ```
> 
> works well.

My `todoService.getAllTodosAsync()` code fragment.

```java
@Asynchronous
CompletableFuture<List<Todo>> getAllTodosAsync() {
    return CompletableFuture
            .supplyAsync(
                    () -> entityManager.createQuery("select t from Todo t", Todo.class).getResultList(),
                    executorService
            );
}
```

**Comment by hantsy** [comment]
> But the thread is not aware of the ThreadLocal RequestScopes, so the scope is not found.  

Why the context can not be propagated automatically between like Spring framework.

**Comment by jansupol** [comment]
In Sring, I assume the random customer-provided thread is not used, the way you use it in your example. In the case you reference, there would be a spring thread factory used I assume?

**Comment by hantsy** [comment]
OK, let's have a look at an example of Spring and Jaxrs.

I have created a sample before to demo `@Async` in Spring, https://github.com/hantsy/spring-puzzles/tree/master/webmvc-async

The repository and controller is like this. The executor is also can be customized.

```java
// Repository 
public interface PostRepository extends JpaRepository<Post, Long> {

    @Async
    CompletableFuture<List<Post>> readAllBy();

}

// controller codes
@RestController
@RequestMapping(value = "/posts")
@RequiredArgsConstructor
public class PostController {
    private final PostRepository posts;

    @GetMapping
    public CompletableFuture<List<Post>> all() {
        return this.posts.readAllBy();
    }

}
```

Compare to the Jaxrs/Jakarta EE 10 example here.

```java
// in a CDI bean
@Asynchronous
CompletableFuture<List<Todo>> getAllTodosAsync() {
    return CompletableFuture
            .supplyAsync(
                    () -> entityManager.createQuery("select t from Todo t", Todo.class).getResultList(),
                    executorService
            );
}

// in a Jaxrs resource
@GET
public CompletableFuture<Response> getAllTodos() {
    return todoService.getAllTodosAsync().thenApply(todos -> Response.ok(todos).build());
}
```

If the CDI bean used custom Asynchronous ContextService, ExecutorService, ThreadFactory, etc can not be called freely, what is the meaning of concurrency?

**Comment by jansupol** [comment]
But all these things you mention here work fine. The request-scoped specific functionality `uriInfo.getBaseUriBuilder()` does not work in the new thread; the new thread does not know about the request and hence the `base`.

**Comment by hantsy** [comment]
But this code fragment does not work. 

```
// in a CDI bean
@Asynchronous
CompletableFuture<List<Todo>> getAllTodosAsync() {
    return CompletableFuture
            .supplyAsync(
                    () -> entityManager.createQuery("select t from Todo t", Todo.class).getResultList(),
                    executorService
            );
}

// in a Jaxrs resource
@GET
public CompletableFuture<Response> getAllTodos() {
    return todoService.getAllTodosAsync().thenApply(todos -> Response.ok(todos).build());
}
```

**Comment by hantsy** [comment]
I think what I talked is a different example in the Jakarta EE and Spring comparison, https://github.com/eclipse-ee4j/glassfish/issues/24121#issuecomment-1304991289, there is no `UriBuilder` in this example.

**Comment by hantsy** [comment]
OK, I have updated my [Jakarta EE Jaxrs Example](https://github.com/hantsy/jakartaee10-sandbox/blob/master/concurrency/src/main/java/com/example/TodoResources.java). 

See the following codes, I marked the `not working` on the method.

```java 
@Path("todos")
@RequestScoped
public class TodoResources {

    private static final Logger LOGGER = Logger.getLogger(TodoResources.class.getName());

    @Context
    ResourceContext resourceContext;

    @Context
    UriInfo uriInfo;

    @Inject
    TodoService todoService;

    @GET // not working 
    public CompletableFuture<Response> getAllTodos() {
        return todoService.getAllTodosAsync().thenApply(todos -> Response.ok(todos).build());
    }

    @GET
    @Path("async1") // works
    public CompletableFuture<Response> getAllTodosAndAsync() {
        var todos = todoService.getAllTodos();
        return CompletableFuture.supplyAsync(() -> todos).thenApply(data -> Response.ok(data).build());
    }

    @POST // extract the UriBuilder, it works
    public CompletionStage<Response> createTodo(Todo todo) throws Exception {
        var uriBuilder = uriInfo.getBaseUriBuilder();
        return todoService.createAsync(todo)
                .thenApply(saved -> Response.created(uriBuilder.path("todos/{id}").build(saved.getId())).build());
    }
}
```

**Comment by OndroMih** [comment]
What exception you get in server.log now?
