### ISSUE TITLE
Exception when enabling a Monitoring Service

### ISSUE THREAD

**Issue by mheydem** [eclipse-ee4j/glassfish#24136]
## Environment Details
* GlassFish Version (and build number): Eclipse GlassFish  6.2.5  (build 6.x-b66-g0159b68 2022-02-12T17:39:59+0000)
* JDK version: OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
* OS: Windows 10
* Database: Oracle

----------

## Problem Description
After enabling a monitoring service an exception is thown immediately and during all following startups.
I tried this for http and transaction monitoring only.
For reproducing you can use the domain1 as delivered and add this to domain.xml:
```
<monitoring-service>
  <module-monitoring-levels http-service="HIGH"></module-monitoring-levels>
</monitoring-service>
```
The Exception
```
[2022-10-19T10:59:37.464+0000] [glassfish 6.2] [WARNING] [NCLS-MON-00511] [jakarta.enterprise.system.tools.monitor] [tid: _ThreadID=90 _ThreadName=pool-16-thread-1] [timeMillis: 1666177177464] [levelValue: 900] [[
  Error while getting Instrumentation object from ProbeAgentMain
java.lang.ClassNotFoundException: org.glassfish.flashlight.agent.ProbeAgentMain
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.glassfish.flashlight.impl.client.ProbeProviderClassFileTransformer.<clinit>(ProbeProviderClassFileTransformer.java:483)
	at org.glassfish.flashlight.impl.client.FlashlightProbeClientMediator.transformProbes(FlashlightProbeClientMediator.java:176)
	at org.glassfish.flashlight.impl.client.FlashlightProbeClientMediator.registerListener(FlashlightProbeClientMediator.java:100)
	at org.glassfish.admin.monitor.StatsProviderManagerDelegateImpl.registerStatsProviderToFlashlight(StatsProviderManagerDelegateImpl.java:626)
	at org.glassfish.admin.monitor.StatsProviderManagerDelegateImpl.enableStatsProvider(StatsProviderManagerDelegateImpl.java:388)
	at org.glassfish.admin.monitor.StatsProviderManagerDelegateImpl.tryToRegister(StatsProviderManagerDelegateImpl.java:171)
	at org.glassfish.admin.monitor.StatsProviderManagerDelegateImpl.register(StatsProviderManagerDelegateImpl.java:134)
	at org.glassfish.external.probe.provider.StatsProviderManager.setStatsProviderManagerDelegate(StatsProviderManager.java:107)
	at org.glassfish.admin.monitor.MonitoringBootstrap.setStatsProviderManagerDelegate(MonitoringBootstrap.java:212)
	at org.glassfish.admin.monitor.MonitoringBootstrap.enableMonitoringForProbeProviders(MonitoringBootstrap.java:621)
	at org.glassfish.admin.monitor.MonitoringBootstrap.enableMonitoring(MonitoringBootstrap.java:164)
	at org.glassfish.admin.monitor.MonitoringBootstrap.handleLevelChange(MonitoringBootstrap.java:553)
	at org.glassfish.admin.monitor.MonitoringBootstrap.changed(MonitoringBootstrap.java:496)
	at org.jvnet.hk2.config.Transactions$ConfigListenerJob.process(Transactions.java:378)
	at org.jvnet.hk2.config.Transactions$ConfigListenerJob.process(Transactions.java:368)
	at org.jvnet.hk2.config.Transactions$ConfigListenerNotifier$1$1.call(Transactions.java:257)
	at org.jvnet.hk2.config.Transactions$ConfigListenerNotifier$1$1.call(Transactions.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```
The exception did not occure in Glassfish 5.1 and 6.0.

**Comment by OndroMih** [comment]
I can't reproduce with [GlassFish 7-M10](https://search.maven.org/artifact/org.glassfish.main.distributions/glassfish/7.0.0-M10/glassfish-distribution) on Linux.

Can you please try with [GlassFish 7-M10](https://search.maven.org/artifact/org.glassfish.main.distributions/glassfish/7.0.0-M10/glassfish-distribution) and report back whether you still observe the issue?

**Comment by mheydem** [comment]
Setup:
- GlassFish 7-M10
- Windows 10
- Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
Instead of the exception the following is logged:
```
[2022-11-28T11:55:31.711812Z] [GlassFish 7.0] [WARNING] [NCLS-MON-00504] [jakarta.enterprise.system.tools.monitor] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 900] [[
  Encountered exception during agent attach]]
  
[2022-11-28T11:55:31.938220Z] [GlassFish 7.0] [INFO] [] [jakarta.enterprise.system.tools.monitor] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Successfully got INSTRUMENTATION: sun.instrument.InstrumentationImpl@38ac8968]]
```

**Comment by OndroMih** [comment]
I confirm I see this error in the log. This is a different issue caused by a change in the JDK 9, see: https://bugs.openjdk.org/browse/JDK-8180425

> The implementation of Attach API has changed in JDK 9 to disallow attaching to the current VM by default. This change should have no impact on tools that use the Attach API to attach to a running VM. It may impact libraries that mis-use this API as a way to get at the `java.lang.instrument` API. The system property `jdk.attach.allowAttachSelf` may be set on the command line to mitigate any compatibility with this change.

I tried adding `-Djdk.attach.allowAttachSelf=true` to the JVM options and it fixed that issue.
