### ISSUE TITLE
CancellationException thrown when calling concurrency @Asynchorous method

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24203]
## Environment Details
* GlassFish Version (and build number): GlassFish 7.0.0 M10
* JDK version: 17
* OS: Windows 10 pro 64bit
* Database: Built-in Derby

----------

## Problem Description

The concurrency @Asynchorous is used to replace the EJB @Asynchorous, so I tried to use concurrency version in a CDI bean.

```java
@ApplicationScoped
public class TodoService {

    @Resource(lookup = "java:module/concurrent/MyExecutor")
    ManagedExecutorService executorService;

    @PersistenceContext
    EntityManager entityManager;

    @Asynchronous
    public CompletableFuture<List<Todo>> getAllTodosAsync() {
        Supplier<List<Todo>> todos = () -> entityManager.createQuery("select t from Todo t", Todo.class).getResultList();
        return executorService.supplyAsync(todos);
    }
...
```

And I wrote the arquillian tests.

```java
@Test
@Order(3)
public void testGetAllTodosAsync() throws Exception {
    todoService.getAllTodosAsync()
            .thenAccept(
                    todos -> {
                        LOGGER.log(Level.INFO, "getAllTodosAsync result: {0}", new Object[]{todos});
                        assertNotNull(todos);
                        assertEquals(3, todos.size());
                    }
            )
            .join();

}
```

## Steps to reproduce

1. Get a copy of my example codes: https://github.com/hantsy/jakartaee10-sandbox/tree/master/concurrency
2. run `mvn clean verify -Parq-glassfish-managed -D"it.test=TodoServiceTest"`
3. It will throw the following exception.
  ```bash
Error:  com.example.it.TodoServiceTest.testGetAllTodosAsync  Time elapsed: 0.067 s  <<< ERROR!
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2480)
	at org.glassfish.enterprise.concurrent.AsynchronousInterceptor.lambda$intercept$0(AsynchronousInterceptor.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:322)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
	... 8 more
  ```

In the GlassFish server.log, I notice there is a message like this.

```bash
@Asynchronous method does not call Asynchronous.Result.complete()...
```

But the EJB @Asynchronous works well.

```java
@Stateless
public class EjbTodoService {
    @PersistenceContext(unitName = "defaultPU")
    EntityManager entityManager;

    @Resource
    ManagedExecutorService executorService;

    @jakarta.ejb.Asynchronous
    public Future<List<Todo>> getAllTodosEjbAsync() {
        Callable<List<Todo>> callable = () -> entityManager.createQuery("select t from Todo t", Todo.class).getResultList();
        return executorService.submit(callable);
    }

}
````

```java
@Test
@Order(1)
public void testGetAllTodosEjbAsync() throws Exception {
    var todos = ejbTodoService.getAllTodosEjbAsync().get(1000, TimeUnit.MILLISECONDS);

    LOGGER.log(Level.INFO, "getAllTodosAsync result: {0}", new Object[]{todos});
    assertNotNull(todos);
    assertEquals(3, todos.size());
}
```

**Comment by renatsaf** [comment]
@
The root cause is in the Jakarta Concurrency implementation (`org.glassfish.concurro:concurro`, repo `eclipse-ee4j/glassfish-concurro`), not in GlassFish itself.

In `AsynchronousInterceptor.executeDirectly`, the `finally` block checked `returnedFuture.isDone()` unconditionally. When an `@Asynchronous` method returns a *different*, still-running `CompletableFuture` — the spec-supported pattern used here via `executorService.supplyAsync(...)` — `isDone()` is `false`, so the interceptor logged the misleading "did not call `Asynchronous.Result.complete()`" message and **cancelled the future already returned to the caller**, surfacing as the `CancellationException`. (It also blocked an executor thread on `returnedFuture.get()`.)

Fix in **eclipse-ee4j/glassfish-concurro#187**: distinguish the two spec cases up front — if the method returns `Asynchronous.Result` itself it must complete it (otherwise log + cancel, unchanged); if it returns a *different* future, bridge its completion non-blockingly via `whenComplete`, propagating the value or exception. Includes regression tests.

This will reach GlassFish once a concurro release containing the fix is published and the `concurro.version` is bumped.
@

**Comment by pzygielo** [comment]
> This will reach GlassFish once a concurro release containing the fix is published and the concurro.version is bumped.

Let's wait with closing this one for that to happen then.
