### ISSUE TITLE
How to use Oracle database driver with EclipseLink?

### ISSUE THREAD

**Issue by suomarte** [eclipse-ee4j/glassfish#24212]
I am trying to upgrade form
- Glassfish 6.0
- Java SE 8

to
- Glassfish 6.2.5
- Java SE 17

### Java SE 8 - GF 6.0

For using the Oracle database driver with EclipseLink the ojdbc8.jar was placed in

`glassfish/domains/domain/lib/ext`

and in domain.xml this was specified

`<jvm-options>-Djava.ext.dirs=${com.sun.aas.javaRoot}/lib/ext${path.separator}${com.sun.aas.javaRoot}/jre/lib/ext${path.separator}${com.sun.aas.instanceRoot}/lib/ext</jvm-options>`

Looks like described in this quite old description
https://docs.oracle.com/cd/E19798-01/821-1752/beaml/index.html

### Java SE 17 - GF 6.2.5

Now, with Java SE 17 the _java.ext.dirs_ option is not valid any longer.
The current glassfish documentation seems not to explain how to to it under the new circumstances.
If I place the ojdbc8.jar in the `glassfish/domains/domain/lib` directory directly, an exception is raised during application startup:
```
java.lang.NoClassDefFoundError: oracle/sql/TIMESTAMP
	at org.eclipse.persistence.platform.database.oracle.Oracle9Platform.<clinit>(Oracle9Platform.java:134)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.newInstanceFromClass(PrivilegedAccessHelper.java:524)
	at org.eclipse.persistence.sessions.DatasourceLogin.setPlatformClassName(DatasourceLogin.java:557)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.updateLogins(EntityManagerSetupImpl.java:2450)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.updateSession(EntityManagerSetupImpl.java:2847)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:750)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:222)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:330)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
	at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:469)
	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:544)
	at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:520)
	at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:205)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:107)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:467)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:199)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:516)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:512)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:511)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:542)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:534)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:533)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1441)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1699)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:510)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:200)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:150)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: oracle.sql.TIMESTAMP
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1212)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1606)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1522)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 60 more
```

Possibly this bug report in Payara is related: https://github.com/payara/Payara/issues/4613

Would you please explain how this should be done correctly?

**Comment by mheydem** [comment]
The workaround described here is working for me: https://github.com/icatproject-contrib/icat-ansible/pull/83#issuecomment-1080535203

1. Move down `glassfish/domains/domain/lib/ext/ojdbc8.jar` to `glassfish/domains/domain/lib`
2. Move `glassfish/modules/org.eclipse.persistence.oracle.jar` to `glassfish/domains/domain/lib`

I leave this bug report open, as this ia just a workaround.

**Comment by OndroMih** [comment]
This is an issue with classloading which on Java 8 used to be fixed with `java.ext.dirs` mechanism. In short, the JDBC driver is OK to be placed in `domain/lib/ojdbc8.jar` but it won't see the Oracle EclipseLink extension needed for correct JPA mappings to the Oracle DB. The solution to move `glassfish/modules/org.eclipse.persistence.oracle.jar` is OK because it moves the Oracle Eclipselink extension on the same level as the JDBC driver.

We'll need to investigate more how to solve this without the work-around. Until then, we could at least document this as the recommended workaround. @mheydem  If you can contribute the documentation, we'd greatly appreciate it. Installing the Oracle JDBC driver is mentioned in the [Administration guide](https://glassfish.org/docs/SNAPSHOT/administration-guide.html#making-the-jdbc-driver-jar-files-accessible) and [Application development guide](https://glassfish.org/docs/SNAPSHOT/application-development-guide.html#oracle-database-enhancements). The Asciidoc sources are here: https://github.com/eclipse-ee4j/glassfish/tree/master/docs

However, this issue might be complicated to fix properly without any hacks. I recommend seeking professional services from companies that provide commercial support for Eclipse GlassFish, see: https://glassfish.org/support.html

**Comment by renatsaf** [comment]
Analyzed and reproduced on current `main` (8.0.5-SNAPSHOT, JDK 21). There are two independent defects here; the second one is the one reported, and the first one masks it on GlassFish 7/8.

## How the `oracle.*` packages are supposed to reach EclipseLink

`modules/org.eclipse.persistence.oracle.jar` is an OSGi fragment of `org.eclipse.persistence.core`, so its classes are defined by the EclipseLink core bundle class loader. The bridge to the (non-OSGi) Oracle driver is `appserver/persistence/oracle-jdbc-driver-packages`, a **framework extension bundle** (`Fragment-Host: system.bundle; extension:=framework`) that exports `oracle.sql`, `oracle.jdbc`, `oracle.jdbc.internal`, `oracle.xdb`, ... from the system bundle. Those exports resolve against the **framework class loader**, which is why the driver has to be installed where that class loader can see it - historically `java.ext.dirs`, i.e. `domain-dir/lib/ext`, exactly as the Administration Guide and the Application Development Guide still describe. That bundle is present and `Resolved` on 8.0.5-SNAPSHOT; the `ExtensionManager$ExtensionManagerWiring.getClassByDelegation` frame in the reported stack trace is that delegation arriving at the framework class loader and finding nothing there.

## Reproducer (no Oracle database needed)

The failure is deployment-time (`JPADeployer` -> `EntityManagerSetupImpl.updateLogins` -> `DatasourceLogin.setPlatformClassName`), before any connection is opened. A WAR with one `@Entity`, a `jta-data-source` pointing at an Oracle pool on a dead `localhost:1521`, and

```xml
<property name="eclipselink.target-database"
          value="org.eclipse.persistence.platform.database.oracle.Oracle21Platform"/>
```

is enough. Driver used: `com.oracle.database.jdbc:ojdbc11:23.9.0.25.07` (confirmed *not* an OSGi bundle - no `Bundle-SymbolicName`, no `Export-Package`, only `Automatic-Module-Name`).

| `org.eclipse.persistence.json` in `modules/` | driver location | `asadmin deploy` result |
| --- | --- | --- |
| no | `domain1/lib` | `ValidationException: Database platform class [...Oracle21Platform] not found` / `ClassNotFoundException` |
| no | `domain1/lib/ext` | same |
| yes | `domain1/lib` | **`NoClassDefFoundError: oracle/sql/TIMESTAMP`** - the issue as reported, same stack including `ExtensionManagerWiring.getClassByDelegation` |
| yes | `domain1/lib/ext` | **works** - gets past the platform class and fails only on `ORA-12541 ... Connection refused` from `oracle.net.nt.TcpNTAdapter` |

## Defect 1: `org.eclipse.persistence.json` is not shipped, so the Oracle extension never resolves

`org.eclipse.persistence.oracle.jar` declares a **mandatory** import:

```
Import-Package: ..., org.eclipse.persistence.json;version="[5.0,6)", ...
```

No bundle in `modules/` exports that package, and no jar in `modules/` even contains `org/eclipse/persistence/json/*`. Consequence:

```
249|Resolved   |    1|EclipseLink Core (5.0.1.v202606291238)
254|Installed  |    1|EclipseLink Oracle Extension (5.0.1.v202606291238)   <- never attaches to its host
```

`asadmin osgi resolve 254` is a no-op. Every `OracleXXPlatform` class is therefore invisible regardless of where the JDBC driver is installed, which is why 7.x/8.x fails earlier than the 6.2.5 report, with `ClassNotFoundException: ...Oracle21Platform` instead of the `oracle.sql` error.

Adding the upstream `org.eclipse.persistence:org.eclipse.persistence.json` artifact (itself a fragment of `org.eclipse.persistence.core`, exporting `org.eclipse.persistence.json`, importing `jakarta.json`) to `modules/` flips bundle 254 to `Resolved` and the platform class loads.

## Defect 2: the driver must be on the server classpath, and since 8.0.4 it can be again

`Oracle9Platform.<clinit>` links `oracle.sql` directly - the bytecode is `ldc class oracle/sql/TIMESTAMP` / `TIMESTAMPTZ` / `TIMESTAMPLTZ` - so the class cannot even initialize without `oracle.sql` on its defining loader. A driver in `domain-dir/lib` lands on the CommonClassLoader, strictly below the module layer, hence the `NoClassDefFoundError`. Java 9 removed `java.ext.dirs`, which is what broke the documented `domain-dir/lib/ext` placement in the first place.

#26060 (shipped in **8.0.4**) puts `<instance-root>/lib/ext/*.jar` back on the server classpath, i.e. onto the parent of the OSGi framework launcher class loader:

```
Adding 1 jar(s) from ...\domains\domain1\lib\ext to the server classpath.
```

With the driver there, the documented procedure works again, and a single copy in `lib/ext` serves both EclipseLink and the connection pool - nothing was left in `domain-dir/lib` in the passing run above. So the documentation is correct as written for 8.0.4+ and needs no change; defect 2 was already fixed, it was just hidden behind defect 1.

## Proposed fix

Add `org.eclipse.persistence.json` next to the existing `org.eclipse.persistence.oracle` entries: `appserver/pom.xml` (dependencyManagement, `${eclipselink.version}`), `appserver/persistence/eclipselink-wrapper/pom.xml`, `appserver/featuresets/web/pom.xml`, `appserver/featuresets/embedded-web/pom.xml` and `appserver/extras/embedded/shell/glassfish-embedded-static-shell/pom.xml`. Its only mandatory import, `jakarta.json`, is already present in the web featureset (`jakarta.json-api` plus Parsson), so the fragment resolves in the Web Profile as well.

Note for 7.x: it does not contain #26060, so `lib/ext` is not on the server classpath there. Users on 7.x need `classpath-suffix`/`system-classpath`, or the extension-jar workaround from this issue, unless #26060 is backported.

**Comment by OndroMih** [comment]
Thanks, @renatsaf , your analysis is helpful and makes sense. Feel free to raise a PR that adds `org.eclipse.persistence.json` to GlassFish. That should fix this issue completely, after #26060 has been fixed. 

I wouldn't backport anything to 7.x for now.
