### ISSUE TITLE
CDI is not available running Jakarta EE Tutorial Examples

### ISSUE THREAD

**Issue by cableDave** [eclipse-ee4j/glassfish#24336]
## Environment Details
* GlassFish Version 7,0.2  (and build number):
* JDK version:
 openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
* OS: Windows 10
* Database: n/a

----------

## Problem Description
Trying to adapt the Jakarta EE Tutorial example code for use with Glassfish 7.x / Jakarta EE 9.x

A provided example fails to complete the maven cargo:run task when the Glassfish 7.0.2 container fails to load.
   `Critical error during deployment: 
   java.lang.IllegalStateException: CDI is not available`

The tutorial sample source code and  POM for the html5  project was not altered

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
	<groupId>org.glassfish-samples</groupId>
        <artifactId>jsf-samples</artifactId>
        <version>6.0-SNAPSHOT</version>
    </parent>
    <artifactId>html5</artifactId>
    <packaging>war</packaging>
    <name>HTML5 JSF Sample</name>
    <build>
        <finalName>html5</finalName>
    </build>
    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>${jakarta.ee.version}</version>
        </dependency>
    </dependencies>
</project>
```
The 'grandparent' pom had settings updated

 ```
   <name>Jakarta EE 9 Samples Main Parent Project</name>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <jakarta.ee.version>9.0.0</jakarta.ee.version>
        <glassfish.version>7.0.2</glassfish.version>
        <integration.container.id>glassfish7x</integration.container.id>
        <glassfish.home>${basedir}/target/cargo/installs/glassfish</glassfish.home>
        <cargo.maven.containerUrl>https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.2.zip</cargo.maven.containerUrl>
        <site.output.dir>${project.build.directory}/staging</site.output.dir>
        <maven.site.skip>true</maven.site.skip>
        <maven.deploy.skip>true</maven.deploy.skip>
        <maven.javadoc.skip>true</maven.javadoc.skip>
        <maven.source.skip>true</maven.source.skip>
        <maven.source.attach>true</maven.source.attach>
    </properties>
```
Note that the compiler source & target were left at 1.8
The original sample project pom properties had
```
 <glassfish.version>6.0.0-RC2</glassfish-version> 
 <cargo.maven.container>http://download.oracle.com/glassfish/5.0/promoted/latest-glassfish.zip</cargo.maven.container>
 <integration.container.id>glassfish5.x</integration.container.id>
```
It appears unlikely that the tutorial was actually updated for compatibility with JDK 11 or JDK 17 and Jakarta EE 9.x - but this does not explain why glassfish 7,0.2 fails to launch from Cargo

Looking at the server log the container has loaded the JBoss Weld libraries

```
### Log Excerpt
[2023-03-08T15:51:24.293316-05:00] [GlassFish 7.0] [INFO] [] [org.jboss.weld.Version] [tid: _ThreadID=94 _ThreadName=Thread-9] [levelValue: 800] [[
  WELD-000900: 5.1.0 (Final)]]

[2023-03-08T15:51:25.139325-05:00] [GlassFish 7.0] [INFO] [] [jakarta.enterprise.system.tools.deployment.common] [tid: _ThreadID=51 _ThreadName=admin-listener(3)] [levelValue: 800] [[
  visiting unvisited references]]

[2023-03-08T15:51:25.226326-05:00] [GlassFish 7.0] [INFO] [] [jakarta.enterprise.system.tools.deployment.common] [tid: _ThreadID=51 _ThreadName=admin-listener(3)] [levelValue: 800] [[
  visiting unvisited references]]

[2023-03-08T15:51:25.235324-05:00] [GlassFish 7.0] [INFO] [] [jakarta.enterprise.system.tools.deployment.common] [tid: _ThreadID=51 _ThreadName=admin-listener(3)] [levelValue: 800] [[
  visiting unvisited references]]

[2023-03-08T15:51:25.385327-05:00] [GlassFish 7.0] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=94 _ThreadName=Thread-9] [levelValue: 800] [[
  WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.]]

[2023-03-08T15:51:25.388326-05:00] [GlassFish 7.0] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=94 _ThreadName=Thread-9] [levelValue: 800] [[
  WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.]]

[2023-03-08T15:51:25.405326-05:00] [GlassFish 7.0] [INFO] [] [org.jboss.weld.Event] [tid: _ThreadID=94 _ThreadName=Thread-9] [levelValue: 800] [[
  WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.]]

[2023-03-08T15:51:25.579326-05:00] [GlassFish 7.0] [INFO] [faces.config.listener.version] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=51 _ThreadName=admin-listener(3)] [levelValue: 800] [[
  Initializing Mojarra 4.0.1 for context '/html5']]

[2023-03-08T15:51:26.367331-05:00] [GlassFish 7.0] [SEVERE] [] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=51 _ThreadName=admin-listener(3)] [levelValue: 1000] [[
  Critical error during deployment: 
java.lang.IllegalStateException: CDI is not available
	at com.sun.faces.util.Util.getCdiBeanManager(Util.java:1494)
	at com.sun.faces.el.ELUtils.addCDIELResolver(ELUtils.java:199)
	at com.sun.faces.el.ELUtils.buildFacesResolver(ELUtils.java:166)
	at com.sun.faces.application.ApplicationAssociate.initializeELResolverChains(ApplicationAssociate.java:416)
	at com.sun.faces.application.applicationimpl.ExpressionLanguage.performOneTimeELInitialization(ExpressionLanguage.java:144)
	at com.sun.faces.application.applicationimpl.ExpressionLanguage.getELResolver(ExpressionLanguage.java:89)
	at com.sun.faces.application.ApplicationImpl.getELResolver(ApplicationImpl.java:200)
	at com.sun.faces.el.ELContextImpl.<init>(ELContextImpl.java:60)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:202)
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3913)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:602)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4452)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:552)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:935)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:917)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:644)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1795)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1483)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:88)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:97)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:262)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:535)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:259)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:529)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:525)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:524)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:555)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:547)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1456)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1825)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1701)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:359)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:202)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:150)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:156)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:453)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:145)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]

[2023-03-08T15:51:26.374332-05:00] [GlassFish 7.0] [SEVERE] [AS-WEB-CORE-00174] [jakarta.enterprise.web.core] [tid: _ThreadID=51 _ThreadName=admin-listener(3)] [levelValue: 1000] [[
  Startup of context /html5 failed due to previous errors]]
```

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce

1. Download Jakarta EE tutorial zip from GitHub 
2. Unzip the glassfish-samples-master
3. Change to the ws/jakartaee9 subdirectory, and use that as the project root directory
4. Edit the jajartaee9  [project root] pom.xml file to provide a Jakarta  EE9 configuration for glassfish 7.0.2
5. Change to the  jsr/html5 directory
6. run mvn package
7. run mvn cargo:run -Dcargo.maven.containerId=glassfish7x -Dglassfish.home=c:\usr\bin\glassfish7

Note, this should also be repeatable using cargo to download anf unzip glassfish

[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
Trying to exercise some of the tutorial 'front end' and security related sub projects.  Will likely try TomEE and the tomee plugin instead of glassfish and cargo to exercise the tutorial code

[//]: # "Please choose one each Type, Component, and Priority label"

 *Type*: Bug
 *Component*:jakarta.enterprise.web.core
 *Priority*: Annoying

**Comment by OndroMih** [comment]
It looks like the `ws/jakartaee9/jsf/html5` project fails to deploy on GlassFish 7 because it uses the deprecated `jakarta.faces.bean.SessionScoped` and `jakarta.faces.bean.ManagedBean` annotations that were removed in Jakarta EE 10 and GlassFish 7. 

The JSF projects should be updated for Jakarta EE 10, it's not an issue with GlassFish 7. Because the annotations aren't on the classpath, they are ignored, which means that there's no CDI bean in the application. Therefore GlassFish doesn't initialize the CDI engine. But there's a reference to a named CDI bean in a JSF page, which fails to resolve without the CDI engine. Even if GlassFish started the CDI engine, no CDI bean would be found to inject into the JSF page.

Try opening [Bean.java](https://github.com/eclipse-ee4j/glassfish-samples/blob/master/ws/jakartaee9/jsf/html5/src/main/java/html5/Bean.java) and replace the annotation `jakarta.faces.bean.SessionScoped` with `jakarta.enterprise.context.SessionScoped`, and `jakarta.faces.bean.ManagedBean` with `jakarta.inject.Named`
