### ISSUE TITLE
ASM9 Support

### ISSUE THREAD

**Issue by mheydem** [eclipse-ee4j/glassfish#24345]
Glassfish 5.1 + Java SE 8
----------
In the days of Glassfish 5.1 and Java SE 8 I had a camel application and was able to deploy it as a WAR. Essentially, this WAR was created as follows:
```
mvn archetype:generate -DarchetypeGroupId="org.apache.camel.archetypes" -DarchetypeArtifactId="camel-archetype-web" -DarchetypeVersion="some older version"
```
Then all I have to do is add a camel.xml with settings for the desired endpoints and routes.

Glassfish 7.0.1 + Java SE 17
----------
Now I'm working with
- Glassfish 7.0.1
- Jakarta EE 10
- Java SE 17 (corretto)

I recreated the WAR by:
```
mvn archetype:generate -DarchetypeGroupId="org.apache.camel.archetypes" -DarchetypeArtifactId="camel-archetype-web" -DarchetypeVersion="3.3.0"
```
and updated the pom.xml for compatibility with Java SE 17:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>da.group</groupId>
  <artifactId>da.artifact</artifactId>
  <version>2.2.0-SNAPSHOT</version>
  <packaging>war</packaging>

  <name>Camel Web Application</name>
  <description>Camel project that deploys the Camel routes as a WAR</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- Camel BOM -->
      <dependency>
        <groupId>org.apache.camel</groupId>
        <artifactId>camel-parent</artifactId>
        <version>3.20.2</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>

    <!-- Camel Dependencies -->
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-spring</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-servlet</artifactId>
    </dependency>

    <!-- Spring Web -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <version>6.0.6</version>
    </dependency>

    <!-- logging -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- testing -->
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-test-spring</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <defaultGoal>install</defaultGoal>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.2</version>
      </plugin>

      <!-- allows running this example with mvn jetty:run -->
      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>11.0.14</version>
        <configuration>
          <webApp>
            <contextPath>/${project.artifactId}</contextPath>
          </webApp>
        </configuration>
      </plugin>

      <!-- plugin to deploy to JBoss AS with: mvn jboss-as:deploy (you can also do redeploy/undeploy) -->
      <plugin>
        <groupId>org.jboss.as.plugins</groupId>
        <artifactId>jboss-as-maven-plugin</artifactId>
        <version>7.9.Final</version>
      </plugin>

    </plugins>
  </build>

</project>
```
Deploying the WAR fails and the following exceptions  (and more of them) apprear in the log:
```
[2023-03-16T12:51:17.418488Z] [GlassFish 7.0] [SEVERE] [] [jakarta.enterprise.system.tools.deployment.common] [tid: _ThreadID=134 _ThreadName=deployment-jar-scanner] [levelValue: 1000] [[
  Exception while visiting org/springframework/web/util/HierarchicalUriComponents$Type.class of size 4114
java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
	at org.objectweb.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:281)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:706)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:336)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:137)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:100)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:321)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:44)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:280)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:269)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]

[2023-03-16T12:51:19.051806Z] [GlassFish 7.0] [SEVERE] [] [jakarta.enterprise.system.tools.deployment.common] [tid: _ThreadID=134 _ThreadName=deployment-jar-scanner] [levelValue: 1000] [[
  Exception while visiting org/springframework/web/service/invoker/HttpServiceMethod$ResponseFunction.class of size 11993
java.lang.UnsupportedOperationException: Record requires ASM8
	at org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:323)
	at org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:953)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:731)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:336)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:137)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:100)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:321)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:44)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:280)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:269)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```
Investigation
----------
- Glassfish 7.0.1 (and also 7.0.2) distributes org.glassfish.hk2:class-model:3.0.3 in glassfish/modules/class-model.jar
- org.glassfish.hk2:class-model:3.0.3 supports up to ASM7 only 
- There is already a commit in 3.0.4-SNAPSHOT which updates to ASM9 and could solve the issue: https://github.com/eclipse-ee4j/glassfish-hk2/commit/a3f00e56789ad02a62d275aea6cde4db72b3412a
- I think ASM9 should be supported for Java SE 17

Request
----------
- Please check if my investigation is correct
- Please integrate next release of org.glassfish.hk2:class-model with ASM9 support into Glassfish
- If you have an idea for a workaround to get it running in Glassfish 7.0.1, please tell me

**Comment by dmatej** [comment]
Can you build hk2 master (`mvn clean install`) then glassfish (`mvn clean install -T4C -Pfastest -Dhk2.version=3.0.4-SNAPSHOT`) and try it again? I would guess both issues should be resolved now, we just need to release them. (In need to hurry yet with one minor commit for hk2).

**Comment by mheydem** [comment]
Building glassfish-hk2
- current master branch
- Java SE 17 (corretto)
- `mvn clean install` build failed, because of failed tests
- `mvn clean install -DskipTests` build success

Building glassfish
- current master branch
- Java SE 17 (corretto)
- `mvn clean install -T4C -Pfastest -Dhk2.version=3.0.4-SNAPSHOT`
    - Error message: `[ERROR] Failed to execute goal org.glassfish.hk2:config-generator:2.5.0-b53:generate-injectors (default-generate-injectors) on project glassfish-jul-extension: Execution default-generate-injectors of goal org.glassfish.hk2:config-generator:2.5.0-b53:generate-injectors failed: Plugin org.glassfish.hk2:config-generator:2.5.0-b53 or one of its dependencies could not be resolved: Could not find artifact org.glassfish.hk2:hk2-config:jar:3.0.4-SNAPSHOT`
    - BUILD FAILURE
-  `mvn clean install -T4C -Pfastest`
    - and setting the version in nucleus/parent/pom.xml
        - project/properties/hk2.version = 3.0.4-SNAPSHOT
        - project/properties/hk2.plugin.version = 3.0.4-SNAPSHOT
    - BUILD SUCCESS

Running glassfish
- JAVA SE 17 (corretto)
- `.\bin\asadmin start-domain domain1 -v`
- Does not start, because of OSGi related errors
```
Launching GlassFish on Felix platform
ERROR: Bundle org.glassfish.hk2.class-model [25] Error starting file:/path/to/glassfish7/glassfish/modules/class-model.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.class-model [25](R 25.0): missing requirement [org.glassfish.hk2.class-model [25](R 25.0)] osgi.wiring.package; (osgi.wiring.package=java.io) Unresolved requirements: [[org.glassfish.hk2.class-model [25](R 25.0)] osgi.wiring.package; (osgi.wiring.package=java.io)])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.class-model [25](R 25.0): missing requirement [org.glassfish.hk2.class-model [25](R 25.0)] osgi.wiring.package; (osgi.wiring.package=java.io) Unresolved requirements: [[org.glassfish.hk2.class-model [25](R 25.0)] osgi.wiring.package; (osgi.wiring.package=java.io)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: Bundle org.glassfish.main.hk2.config-types [44] Error starting file:/path/to/glassfish7/glassfish/modules/config-types.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.hk2.config-types [44](R 44.0): missing requirement [org.glassfish.main.hk2.config-types [44](R 44.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.glassfish.hk2.api [117](R 117.0): missing requirement [org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io)] Unresolved requirements: [[org.glassfish.main.hk2.config-types [44](R 44.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0)))])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.hk2.config-types [44](R 44.0): missing requirement [org.glassfish.main.hk2.config-types [44](R 44.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.glassfish.hk2.api [117](R 117.0): missing requirement [org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io)] Unresolved requirements: [[org.glassfish.main.hk2.config-types [44](R 44.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: Bundle org.glassfish.main.core.glassfish [106] Error starting file:/path/to/glassfish7/glassfish/modules/glassfish.jar (org.osgi.framework.BundleException: Activator start error in bundle org.glassfish.main.core.glassfish [106].)
java.lang.NoClassDefFoundError: com/sun/enterprise/module/bootstrap/BootException
        at com.sun.enterprise.glassfish.bootstrap.osgi.GlassFishMainActivator.startNonEmbedded(GlassFishMainActivator.java:147)
        at com.sun.enterprise.glassfish.bootstrap.osgi.GlassFishMainActivator.start(GlassFishMainActivator.java:117)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.sun.enterprise.module.bootstrap.BootException not found by org.glassfish.main.core.glassfish [106]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 8 more
ERROR: Bundle org.glassfish.hk2.api [117] Error starting file:/path/to/glassfish7/glassfish/modules/hk2-api.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.api [117](R 117.0): missing requirement [org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io) Unresolved requirements: [[org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io)])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.api [117](R 117.0): missing requirement [org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io) Unresolved requirements: [[org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: Bundle org.glassfish.main.hk2.config [118] Error starting file:/path/to/glassfish7/glassfish/modules/hk2-config.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.hk2.config [118](R 118.0): missing requirement [org.glassfish.main.hk2.config [118](R 118.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.glassfish.hk2.api [117](R 117.0): missing requirement [org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io)] Unresolved requirements: [[org.glassfish.main.hk2.config [118](R 118.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0)))])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.main.hk2.config [118](R 118.0): missing requirement [org.glassfish.main.hk2.config [118](R 118.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.glassfish.hk2.api [117](R 117.0): missing requirement [org.glassfish.hk2.api [117](R 117.0)] osgi.wiring.package; (osgi.wiring.package=java.io)] Unresolved requirements: [[org.glassfish.main.hk2.config [118](R 118.0)] osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.hk2.utilities)(version>=3.0.0)(!(version>=4.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: Bundle org.glassfish.hk2.locator [120] Error starting file:/path/to/glassfish7/glassfish/modules/hk2-locator.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.locator [120](R 120.0): missing requirement [org.glassfish.hk2.locator [120](R 120.0)] osgi.wiring.package; (osgi.wiring.package=java.io) Unresolved requirements: [[org.glassfish.hk2.locator [120](R 120.0)] osgi.wiring.package; (osgi.wiring.package=java.io)])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.locator [120](R 120.0): missing requirement [org.glassfish.hk2.locator [120](R 120.0)] osgi.wiring.package; (osgi.wiring.package=java.io) Unresolved requirements: [[org.glassfish.hk2.locator [120](R 120.0)] osgi.wiring.package; (osgi.wiring.package=java.io)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: Bundle org.glassfish.hk2.utils [122] Error starting file:/path/to/glassfish7/glassfish/modules/hk2-utils.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.utils [122](R 122.0): missing requirement [org.glassfish.hk2.utils [122](R 122.0)] osgi.wiring.package; (osgi.wiring.package=java.beans) Unresolved requirements: [[org.glassfish.hk2.utils [122](R 122.0)] osgi.wiring.package; (osgi.wiring.package=java.beans)])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.utils [122](R 122.0): missing requirement [org.glassfish.hk2.utils [122](R 122.0)] osgi.wiring.package; (osgi.wiring.package=java.beans) Unresolved requirements: [[org.glassfish.hk2.utils [122](R 122.0)] osgi.wiring.package; (osgi.wiring.package=java.beans)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: Bundle org.glassfish.hk2.osgi-adapter [240] Error starting file:/path/to/glassfish7/glassfish/modules/osgi-adapter.jar (org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.osgi-adapter [240](R 240.0): missing requirement [org.glassfish.hk2.osgi-adapter [240](R 240.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.module.bootstrap)(version>=3.0.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.glassfish.hk2.core [119](R 119.0): missing requirement [org.glassfish.hk2.core [119](R 119.0)] osgi.wiring.package; (osgi.wiring.package=java.io)] Unresolved requirements: [[org.glassfish.hk2.osgi-adapter [240](R 240.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.module.bootstrap)(version>=3.0.0)(!(version>=4.0.0)))])
org.osgi.framework.BundleException: Unable to resolve org.glassfish.hk2.osgi-adapter [240](R 240.0): missing requirement [org.glassfish.hk2.osgi-adapter [240](R 240.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.module.bootstrap)(version>=3.0.0)(!(version>=4.0.0))) [caused by: Unable to resolve org.glassfish.hk2.core [119](R 119.0): missing requirement [org.glassfish.hk2.core [119](R 119.0)] osgi.wiring.package; (osgi.wiring.package=java.io)] Unresolved requirements: [[org.glassfish.hk2.osgi-adapter [240](R 240.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.module.bootstrap)(version>=3.0.0)(!(version>=4.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:93)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:31)
Caused by: org.glassfish.embeddable.GlassFishException: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:152)
        at org.glassfish.embeddable.GlassFishRuntime._bootstrap(GlassFishRuntime.java:133)
        at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:96)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:139)
        ... 6 more
Caused by: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.getGlassFishRuntime(OSGiGlassFishRuntimeBuilder.java:191)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:150)
        ... 9 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:93)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:31)
Caused by: org.glassfish.embeddable.GlassFishException: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:152)
        at org.glassfish.embeddable.GlassFishRuntime._bootstrap(GlassFishRuntime.java:133)
        at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:96)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:139)
        ... 6 more
Caused by: org.glassfish.embeddable.GlassFishException: No GlassFishRuntime available
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.getGlassFishRuntime(OSGiGlassFishRuntimeBuilder.java:191)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishRuntimeBuilder.build(OSGiGlassFishRuntimeBuilder.java:150)
        ... 9 more
```
Check for ASM9 support not yet done, because of the difficulties described above.
Do you have suggestions on how to handle the OSGi related errors?

**Comment by avpinchuk** [comment]
I confirm this behavior. This happens due to HK2 3.0.4-SNAPSHOT bundle manifests imports `java.*` packages by default. I suggest PR to HK2 repository to fix this eclipse-ee4j/glassfish-hk2#809.

But we have another problem - hk2 version in `appserver/web/jersey-ejb-component-provider/pom.xml`. HK2 bundles exports version 3.0.4, but EJB component provider requires exactly `${hk2.version}`, 3.0.4-SNAPSHOT in our case.

We have two options to solve it:

1. Remove `version="${hk2.version}` for `org.glassfish.hk2.*` in `appserver/web/jersey-ejb-component-provider/pom.xml`
```pom
    ...
     <configuration>
         <instructions>
             <Import-Package>
                 jakarta.annotation.*;version="${jakarta.annotation-api.version}",
                 org.glassfish.hk2.*;version="${hk2.version}",
                 *
             </Import-Package>
             <Export-Package>
                 org.glassfish.jersey.gf.ejb.internal,
             </Export-Package>
       </instructions>
       ...
```
2. Remove `dropVersionComponent` property from `glassfish-hk2`'s `pom.xml` (parent-hk2 pom). This preserve the qualifier part of version for exported packages.

@dmatej, what you think about that?

**Comment by dmatej** [comment]
Oh, I remember, OSGI transforms 3.0.4-SNAPSHOT to 3.0.4.SNAPSHOT, but not when it is set explicitly. I think I resolved it somehow in another project, I will find it ...

**Comment by avpinchuk** [comment]
@dmatej, property definition with `-Dhk2.version` doesn't work because `org.glassfish.hk2.config-generator` have it's own `hk2.version=2.5.0-b53` property, defined in `maven-plugins-2.5.0-b53.pom` parent POM. When we redefine it with -D option, then maven attempt to get `hk2-config` artifact with redefined version which does not exists.

**Comment by dmatej** [comment]
On current master, Maven 3.9.0 and JDK17 on my laptop:
```
mvn clean install -T4C -Pfastest -Dhk2.version=3.0.4-SNAPSHOT
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:31 min (Wall Clock)
[INFO] Finished at: 2023-03-28T00:11:06+02:00
[INFO] ------------------------------------------------------------------------
```
Is it ok now or did I understand wrong?

**Comment by avpinchuk** [comment]
Probably my information obsoleted. I tried build three days ago :-)

**Comment by mheydem** [comment]
Environment:
- Windows 10
- Corretto-17.0.6.10.1
- Maven 3.8.6

Building glassfish-hk2
- current master branch (e231c8f4f52db48d1d8833a6c70700662f80bfae)
- mvn clean install BUILD FAILURE, org.glassfish.hk2.xml.test.pbuf.PBufPreCompileTest FAILS
- mvn clean install -DskipTests BUILD SUCCESS

Building glassfish
- current master branch (a9dbe0168dba01bfd52f5b0257282d9d8504621b)
- mvn clean install -T4C -Pfastest -Dhk2.version=3.0.4-SNAPSHOT
  - `[ERROR] Failed to execute goal org.glassfish.hk2:config-generator:2.5.0-b53:generate-injectors (default-generate-injectors) on project glassfish-jul-extension: Execution default-generate-injectors of goal org.glassfish.hk2:config-generator:2.5.0-b53:generate-injectors failed: Plugin org.glassfish.hk2:config-generator:2.5.0-b53 or one of its dependencies could not be resolved: Could not find artifact org.glassfish.hk2:hk2-config:jar:3.0.4-SNAPSHOT`
  - BUILD FAILURE
- mvn clean install -T4C -Pfastest
  - in nucleus/parent/pom.xml: project/properties/hk2.version = 3.0.4-SNAPSHOT
  - BUILD SUCCESS

Modifications to the camel application (mentioned in first comment)
- added a beans.xml with bean-discovery-mode="all"
- upgrade dependency: org.apache.camel:camel-parent:pom:4.0.0-M2 (for jakarta namespace support)

Running glassfish
- domain1 startup SUCCESSFUL
- the camel application (mentioned in first comment) deployment SUCCESSFUL
- Camel Servlet example WORKS

**Comment by dmatej** [comment]
> Building glassfish-hk2
> current master branch (e231c8f4f52db48d1d8833a6c70700662f80bfae)
> mvn clean install BUILD FAILURE, org.glassfish.hk2.xml.test.pbuf.PBufPreCompileTest FAILS

In my case, same commit, clean workspace:
```
/repo/git/hk2$ mvn -version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /.../apache-maven-3.9.0
Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/jdk-17.0.4.1+1
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-69-generic", arch: "amd64", family: "unix"
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:56 min
[INFO] Finished at: 2023-03-28T16:29:42+02:00
[INFO] ------------------------------------------------------------------------
```
That smells, can someone confirm there is some issue on Windows or what?

The second failure related to `config-generator:2.5.0-b53` - now I understand the comment from @avpinchuk - in my case it works because I have that snapshot built locally, so they it is available to maven. That's why it always passed in my case.

**Comment by avpinchuk** [comment]
@dmatej, I confirm on Windows. Later I'll try on Ubuntu too.

**Comment by dmatej** [comment]
> @dmatej, I confirm on Windows. Later I'll try on Ubuntu too.

I tried to google something about it, it seems you have to install something on windows: https://www.geeksforgeeks.org/how-to-install-protocol-buffers-on-windows/

**Comment by avpinchuk** [comment]
So, I finished )

On **Ubuntu 22.04**

* build *glassfish-hk2* with `mvn clean install -DskipTests` is OK
* build *glassfish* with `mvn clean install -Pfastest -T4C -Dhk2.version=3.0.4-SNAPSHOT` is OK

On **Windows 10**

First, delete local maven cache (`%usrprofile%\.m2\repository` by default). Then same steps as for Linux:

* build *glassfish-hk2* with `mvn clean install -DskipTests` is OK
* build *glassfish* with `mvn clean install -Pfastest -T4C -Dhk2.version=3.0.4-SNAPSHOT` is OK

**Comment by dmatej** [comment]
Good! Meanwhile @arjantijms started preparing the release and maven-javadoc-plugin was quite critical to the HK2 sources, so we had to push HK2 yet bit forward: https://github.com/eclipse-ee4j/glassfish-hk2/pull/816

**Comment by dmatej** [comment]
I think it is fixed now, if you would find yet something, feel free to create another issue. 
About plugins and their dependencies - we are aware of some issues and "obsolescence", which should be slowly improved in the future.
