### ISSUE TITLE
[7.0.4] Deployment fail with Hibernate 6.2.2.Final

### ISSUE THREAD

**Issue by ctabin** [eclipse-ee4j/glassfish#24414]
Hello,

The deployment of an application with Hibernate 6.2.2.Final fails with the following error:

```
java.lang.ClassCircularityError: org/hibernate/bytecode/enhance/spi/EnhancementContextWrapper
        at org.hibernate.jpa.internal.enhance.EnhancingClassTransformerImpl.transform(EnhancingClassTransformerImpl.java:50)
        at org.glassfish.persistence.jpa.ServerProviderContainerContractInfo$1.transform(ServerProviderContainerContractInfo.java:85)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:718)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at org.glassfish.common.util.GlassfishUrlClassLoader.loadClass(GlassfishUrlClassLoader.java:115)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:166)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1380)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1451)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:142)
        at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:222)
        at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:126)
        at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:319)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:546)
        at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:326)
        at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:168)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepareBundle(EarDeployer.java:286)
        at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:146)
        at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:142)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnBundles(EarDeployer.java:213)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllTypedBundles(EarDeployer.java:221)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllBundles(EarDeployer.java:246)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:142)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:469)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:259)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:529)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:525)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:524)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:555)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:547)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1456)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1825)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1701)
        at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:108)
        at <main>
```

The deployment is successful with Hibernate 6.1.7.Final 

The same [issue](https://github.com/payara/Payara/issues/6248) is happening in the latest Payara version. There is a reproducer [here](https://github.com/grommitz/hibernate-deployment-issue-reproducer).

There was a ticket in Hibernate ([HH-16299](https://hibernate.atlassian.net/browse/HHH-16299)) but it seems it's GlassFish related (and also [this PR](https://github.com/hibernate/hibernate-orm/pull/5977)).

### Environment

* JDK 17
* glassfish-embedded-all 7.0.4
* Linux Debian

**Comment by avpinchuk** [comment]
@ctabin, what about GlassFish full or web?

**Comment by ctabin** [comment]
@avpinchuk I didn't test with GlassFish full/web, only with glassfish-embedded-all. Maybe @grommitz could tell ?

**Comment by avpinchuk** [comment]
So, deployment on the GlassFish full profile failed too, but with `StackOverflowError`.

**Comment by ctabin** [comment]
@avpinchuk Thanks for your test.

On our side, we just did the following: instead of just declaring the dependency in our EAR (which is deployed programmatically), we *also* declared the Hibernate 6.2.2.Final dependency in our main application (which actually does only deploy our EAR in glassfish-embedded-all) and then the deployment was successful.

So hopefully it can help to find the error source. :pray:

**Comment by avpinchuk** [comment]
@ctabin, try to add next two properties in your PU definition:

```xml
...
<property name="hibernate.enhancer.enableDirtyTracking" value="false"/>
<property name="hibernate.enhancer.enableLazyInitialization" value="false"/>
...
```

This is because prior to Hibernate 6.2 they evaluates as `false` when was not defined, and GlassFish did not use Hibernate bytecode enhancer at all. In Hibernate 6.2 this was chanded, they have value `true` by default.

You can reproduce this behavior on Hibernate 6.1.7.Final if you define this properties as `true`.

I hope this helps. Regards.

**Comment by ctabin** [comment]
@avpinchuk Hi,

Thanks for the hint, that did the trick and we are able to deploy our application \o/
Do you want to keep this issue open ? It could be worth adding a note in the documentation about it.

**Comment by avpinchuk** [comment]
I think this is a temporary solution. Later I'll try to look deeper at this issue.

**Comment by ctabin** [comment]
@avpinchuk I just tried hibernate 6.2.4 with GlassFish 7.0.5 and... still hit the same issue:

```
java.lang.ClassCircularityError: org/hibernate/bytecode/enhance/spi/EnhancementContextWrapper
        at org.hibernate.jpa.internal.enhance.EnhancingClassTransformerImpl.transform(EnhancingClassTransformerImpl.java:50)
        at org.glassfish.persistence.jpa.ServerProviderContainerContractInfo$1.transform(ServerProviderContainerContractInfo.java:85)
        at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:718)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at org.glassfish.common.util.GlassfishUrlClassLoader.loadClass(GlassfishUrlClassLoader.java:115)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:166)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1380)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1451)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:142)
        at org.glassfish.persistence.jpa.PersistenceUnitLoader.loadPU(PersistenceUnitLoader.java:222)
        at org.glassfish.persistence.jpa.PersistenceUnitLoader.<init>(PersistenceUnitLoader.java:126)
        at org.glassfish.persistence.jpa.JPADeployer$1.visitPUD(JPADeployer.java:319)
        at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:546)
        at org.glassfish.persistence.jpa.JPADeployer.createEMFs(JPADeployer.java:326)
        at org.glassfish.persistence.jpa.JPADeployer.prepare(JPADeployer.java:168)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepareBundle(EarDeployer.java:286)
        at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:146)
        at org.glassfish.javaee.full.deployment.EarDeployer$1.doBundle(EarDeployer.java:142)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnBundles(EarDeployer.java:213)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllTypedBundles(EarDeployer.java:221)
        at org.glassfish.javaee.full.deployment.EarDeployer.doOnAllBundles(EarDeployer.java:246)
        at org.glassfish.javaee.full.deployment.EarDeployer.prepare(EarDeployer.java:142)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepareModule(ApplicationLifecycle.java:986)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:469)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:259)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
```

**Comment by avpinchuk** [comment]
@ctabin, I need reproducer for GF

**Comment by ctabin** [comment]
@avpinchuk [Here](https://github.com/ctabin/gf-test) you are :wink:

**Comment by avpinchuk** [comment]
@ctabin, I'll take a look tomoroiw (or already today ;-) ). Now I have 1:40 AM

**Comment by avpinchuk** [comment]
@ctabin, solution here #24448.
