### ISSUE TITLE
application fails do deploy to standalone instance or cluster, but works on server instance

### ISSUE THREAD

**Issue by mirozitnansky** [eclipse-ee4j/glassfish#24514]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 7.0.6  (commit: 9e82903b2afcab9478003fb5adb7bd6a466e4982)
* JDK version:  zulu17.44.15-ca-jdk17.0.8
* OS: Centos7
* Database: Oracle

----------

## Problem Description
Application migrated from javax+jdk11 compatible to jakarta+jdk17. When deployed in default server instance of domain1, works fine.

When we tried to deploy same war into cluster (or standalone instance), deployment fails with following exception:

```
[2023-07-19T10:50:02.729035+02:00] [GF 7.0.6] [SEVERE] [AS-WEB-CORE-00108] [jakarta.enterprise.web.core] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 1000] [[
  ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: org.glassfish.deployment.common.DeploymentException: Error in generating security policy for AxaAttendance-2.06 -- Error in generating security policy for AxaAttendance-2.06 -- Operation invoked on closed or deleted PolicyConfiguration.
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4467)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:551)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:935)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:917)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:644)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1795)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1483)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:88)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:97)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:262)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:535)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:242)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:356)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:410)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpAllTheWay.go(CurrentTaskFuture.java:561)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:133)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture.go(CurrentTaskFuture.java:128)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.proceedTo(AsyncRunLevelContext.java:511)
	at org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl.proceedTo(RunLevelControllerImpl.java:48)
	at com.sun.enterprise.v3.server.AppServerStartup.proceedTo(AppServerStartup.java:498)
	at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:302)
	at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:209)
	at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:200)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:55)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:38)
	at com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl.start(EmbeddedOSGiGlassFishImpl.java:50)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:38)
	at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishImpl.start(OSGiGlassFishImpl.java:46)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:93)
	at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:31)
Caused by: org.glassfish.deployment.common.DeploymentException: Error in generating security policy for AxaAttendance-2.06 -- Error in generating security policy for AxaAttendance-2.06 -- Operation invoked on closed or deleted PolicyConfiguration.
	at org.glassfish.exousia.modules.locked.SimplePolicyConfiguration.assertStateIsOpen(SimplePolicyConfiguration.java:686)
	at org.glassfish.exousia.modules.locked.SimplePolicyConfiguration.removeUncheckedPolicy(SimplePolicyConfiguration.java:425)
	at org.glassfish.exousia.AuthorizationService.removeStatementsFromPolicy(AuthorizationService.java:266)
	at com.sun.enterprise.security.web.integration.WebSecurityManager.release(WebSecurityManager.java:342)
	at com.sun.enterprise.security.ee.SecurityDeployer.loadWebPolicy(SecurityDeployer.java:238)
	at com.sun.enterprise.security.ee.SecurityDeployer.commitWebPolicy(SecurityDeployer.java:261)
	at com.sun.enterprise.security.ee.SecurityDeployer$AppDeployEventListener.event(SecurityDeployer.java:146)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:107)
	at com.sun.enterprise.web.WebContainer.afterServletContextInitializedEvent(WebContainer.java:569)
	at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:623)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4450)
	... 45 more
]]
```
Full server log containing mentioned exception and following.
[server.log](https://github.com/eclipse-ee4j/glassfish/files/12105131/server.log)

## Steps to reproduce
There are no steps. 
If deployed to default server instance (_server-config_), exception does not happen.
If deployed to newly created cluster (or standalone) instance based on _default-config_.

Oracle JDBC driver present in lib folder and JDBC pool configured in domain.

Only way to reproduce would be to provide deployable war. 

## Impact of Issue
Application cannot be deployed to cluster.

We tried to delete _generated_ and _osgi-cache_ in domain and instance folders, didn't help.

**Comment by pzygielo** [comment]
Please provide the section
## Steps to reproduce

**Comment by mirozitnansky** [comment]
> Please provide the section
> 
> ## Steps to reproduce

added

**Comment by mirozitnansky** [comment]
As this exception arises outside of application, we need to at least point to possible problem. It that possible?

```
[2023-07-19T10:50:02.729035+02:00] [GF 7.0.6] [SEVERE] [AS-WEB-CORE-00108] [jakarta.enterprise.web.core] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 1000] [[
  ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: org.glassfish.deployment.common.DeploymentException: Error in generating security policy for AxaAttendance-2.06 -- Error in generating security policy for AxaAttendance-2.06 -- Operation invoked on closed or deleted PolicyConfiguration.
```

**Comment by pzygielo** [comment]
If this happens in exousia
https://github.com/eclipse-ee4j/glassfish/blob/c4a354ba5aae7d3ebdac36b31c75633de02b0b74/impl/src/main/java/org/glassfish/exousia/modules/locked/SimplePolicyConfiguration.java#L684-L688

maybe https://projects.eclipse.org/projects/ee4j.exousia could help.

**Comment by mirozitnansky** [comment]
We found that this happens only if virtual server is created. So it's not related to standalone instance, it happens also in default server instance.

Deploy command, when _--virtualservers_ is not present, it tries to deploy to every virutal server present in configuration.
In server.log, when virtual server is present this looks like deploying is running twice
```
[2023-07-19T10:49:59.912670+02:00] [GF 7.0.6] [INFO] [] [org.eclipse.krazo.servlet.KrazoContainerInitializer] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Eclipse Krazo version 3.0.1 started]]

[2023-07-19T10:49:59.923043+02:00] [GF 7.0.6] [INFO] [] [org.glassfish.soteria.servlet.SamRegistrationInstaller] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Initializing Soteria 3.0.3 for context '/AxaAttendance-2.06']]

[2023-07-19T10:50:00.139544+02:00] [GF 7.0.6] [INFO] [] [org.glassfish.tyrus.servlet.TyrusServletContainerInitializer] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Registering WebSocket filter for url pattern /*]]

[2023-07-19T10:50:00.188523+02:00] [GF 7.0.6] [INFO] [] [org.omnifaces.ApplicationInitializer] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Using OmniFaces version 4.1]]

[2023-07-19T10:50:00.315855+02:00] [GF 7.0.6] [INFO] [faces.config.listener.version] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Initializing Mojarra 4.0.2 for context '/AxaAttendance-2.06']]

[2023-07-19T10:50:01.492173+02:00] [GF 7.0.6] [INFO] [] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Monitoring file:/home/payara/glassfish7/0.6/glassfish/nodes/appesktest1/dochadzkaInst1/applications/AxaAttendance-2.06/WEB-INF/faces-config.xml for modifications]]

[2023-07-19T10:50:01.548919+02:00] [GF 7.0.6] [INFO] [] [org.primefaces.webapp.PostConstructApplicationEventListener] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Running on PrimeFaces 12.0.0]]

[2023-07-19T10:50:02.356696+02:00] [GF 7.0.6] [INFO] [] [org.eclipse.krazo.servlet.KrazoContainerInitializer] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Eclipse Krazo version 3.0.1 started]]

[2023-07-19T10:50:02.357916+02:00] [GF 7.0.6] [INFO] [] [org.glassfish.soteria.servlet.SamRegistrationInstaller] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Initializing Soteria 3.0.3 for context '/AxaAttendance-2.06']]

[2023-07-19T10:50:02.360306+02:00] [GF 7.0.6] [INFO] [] [org.glassfish.tyrus.servlet.TyrusServletContainerInitializer] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Registering WebSocket filter for url pattern /*]]

[2023-07-19T10:50:02.389967+02:00] [GF 7.0.6] [INFO] [] [org.omnifaces.ApplicationInitializer] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Using OmniFaces version 4.1]]

[2023-07-19T10:50:02.396040+02:00] [GF 7.0.6] [INFO] [faces.config.listener.version] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Initializing Mojarra 4.0.2 for context '/AxaAttendance-2.06']]

[2023-07-19T10:50:02.703105+02:00] [GF 7.0.6] [INFO] [] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Monitoring file:/home/payara/glassfish7/0.6/glassfish/nodes/appesktest1/dochadzkaInst1/applications/AxaAttendance-2.06/WEB-INF/faces-config.xml for modifications]]

[2023-07-19T10:50:02.708041+02:00] [GF 7.0.6] [INFO] [] [org.primefaces.webapp.PostConstructApplicationEventListener] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 800] [[
  Running on PrimeFaces 12.0.0]]

[2023-07-19T10:50:02.711849+02:00] [GF 7.0.6] [SEVERE] [AS-WEB-CORE-00174] [jakarta.enterprise.web.core] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 1000] [[
  Startup of context /AxaAttendance-2.06 failed due to previous errors]]

[2023-07-19T10:50:02.729035+02:00] [GF 7.0.6] [SEVERE] [AS-WEB-CORE-00108] [jakarta.enterprise.web.core] [tid: _ThreadID=1 _ThreadName=main] [levelValue: 1000] [[
  ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: org.glassfish.deployment.common.DeploymentException: Error in generating security policy for AxaAttendance-2.06 -- Error in generating security policy for AxaAttendance-2.06 -- Operation invoked on closed or deleted PolicyConfiguration.
```

If we explicitly set property  _--virtualservers server_, deployment works fine even when other virtual server exists.

Now we have problem to create reproducer, because we are unable to address specific module which is responsible for this.
If we remove majority of dependencies (application is much simpler), exception won't happen.

Can you give us hint, how to address specific module, which can be cause of this error when virtual server is present?

**Comment by OndroMih** [comment]
@dmatej, @pzygielo , would you please reopen this issue?

**Comment by avpinchuk** [comment]
It happens even when we define `--virtualservers` argument with a valid list of the virtual servers. I.e., when we try to deploy our application to two or more virtual servers, implicitly (without `--virtualservers` argument, in this case application should be deployed to all virtual servers but `__asadmin`) or explicitly (with `--virtualservers` argument contains a valid server list).

**Comment by mirozitnansky** [comment]
That's what I wrote in my last comment. If there are any virtual server defined, deploy works only if _--virtualserver server_ is explicitly specified, so it's deployning only to one virutal server (_server_ is also defined as virtual server by default)

**Comment by avpinchuk** [comment]
> That's what I wrote in my last comment. If there are any virtual server defined, deploy works only if _--virtualserver server_ is explicitly specified, so it's deployning only to one virutal server (_server_ is also defined as virtual server by default)

Not only. If you define `--virtualservers server,vServer1`, deploy failed too.

**Comment by avpinchuk** [comment]
@arjantijms, I want to suggest the PR for Exousia that correct this issue. Which branch should I use for that?

**Comment by arjantijms** [comment]
It's the 2.1 branch. At the time something went wrong went the creation of the default branch, and somehow "1.0" was set to the default.

I'll ask at gitlab to rename 2.1 to "main".

**Comment by arjantijms** [comment]
@mirozitnansky we have prepared an early build here which should fix the issue: https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24597/1/artifact/bundles/glassfish.zip

If you want, please check if this indeed fixes your issue.

**Comment by mirozitnansky** [comment]
I can confirm on 7.0.9 deployment to virtual server works as expected.

**Comment by arjantijms** [comment]
> I can confirm on 7.0.9 deployment to virtual server works as expected.

Thanks a lot for the confirmation :)

**Comment by mirozitnansky** [comment]
> > I can confirm on 7.0.9 deployment to virtual server works as expected.
> 
> Thanks a lot for the confirmation :)

Thanks a lot for fixing. ;)
