### ISSUE TITLE
jakarta.ejb.CreateException: Initialization failed for Singleton SampleDataGenerator

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24646]
Today I try to update [Cargotacker(my personal fork)](https://github.com/hantsy/cargotracker) to Jakarta EE 10, and there is an interesting issue when running all tests on Github actions.

The tests are working well on my Windows 10, one test failed on Glassfish on Github actions/Ubuntu.

**All tests are passed on Wildfly, both Windows 10 and Ubuntu(Github actions)**

## Environment Details
* GlassFish Version (and build number): 7.0.9
* JDK version: 21
* OS: Windows/Ubuntu
* Database: Postgres

----------

## Problem Description

```bash
Caused by: org.jboss.arquillian.container.glassfish.clientutils.GlassFishClientException:
 exit_code: FAILURE, message: Error occurred during deployment: 
Exception while loading the app : jakarta.ejb.CreateException: 
Initialization failed for Singleton SampleDataGenerator.
```

The Sample Data Generator is a simple `@Singleton` EJB with `@Startup` to initialize some Sample data, https://github.com/hantsy/cargotracker/blob/master/src/main/java/org/eclipse/cargotracker/application/util/SampleDataGenerator.java

## Steps to reproduce

The GitHub actions build stack log: https://github.com/hantsy/cargotracker/actions/runs/6604412814/job/17938518306#step:5:221

It only occurs on Github actions with a Ubuntu os.

1. clone https://github.com/hantsy/cargotracker
2. run `docker compose up postgres` to serve a Postgres
3. run the following test.

    ```bash 
    mvn clean verify -P"arq-glassfish-managed" -D"it.test=CargoMonitoringServiceTest"
    ```

**Comment by pzygielo** [comment]
server.log:
```
[2023-10-22T18:05:02.157484+02:00] [GF 7.0.9] [SEVERE] [] [jakarta.enterprise.system.core] [tid: _ThreadID=45 _ThreadName=admin-listener(3)] [levelValue: 1000] [[
  Exception while loading the app : jakarta.ejb.CreateException: Initialization failed for Singleton SampleDataGenerator
jakarta.ejb.CreateException: Initialization failed for Singleton SampleDataGenerator
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:450)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:620)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:362)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:195)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:156)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:134)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:137)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:97)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:262)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:353)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:535)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:259)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:570)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:566)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:596)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:588)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:376)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:587)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1478)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1847)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1723)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:221)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:202)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:241)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:305)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.post(TemplateListOfResource.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:287)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:156)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:425)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: relation "cargo" does not exist
  Position: 330
Error Code: 0
Call: SELECT ID, calculated_at, ETA, unloaded_at_dest, MISDIRECTED, routing_status, transport_status, next_expected_handling_event_type, next_expected_location_id, next_expected_voyage_id, current_voyage_id, last_event_id, last_known_location_id, spec_arrival_deadline, spec_destination_id, spec_origin_id, tracking_id, origin_id FROM CARGO
```

**Comment by pzygielo** [comment]
Once some other test creates required schema objects I'm getting:
```
INFO:  Running test:: CargoMonitoringServiceTest#testCargoStatus ... 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.29 s -- in org.eclipse.cargotracker.interfaces.booking.rest.CargoMonitoringServiceTest
[INFO] org.eclipse.cargotracker.interfaces.booking.rest.CargoMonitoringServiceTest.testCargoStatus -- Time elapsed: 0.474 s
Stopping container using command: [java, -jar, /tmp/cargotracker/target/glassfish7/glassfish/modules/admin-cli.jar, stop-domain, --kill, -t]
Waiting finished after 271 ms.
Stopping database using command: [java, -jar, /tmp/cargotracker/target/glassfish7/glassfish/modules/admin-cli.jar, stop-database, -t]
Sun Oct 22 18:39:19 CEST 2023 : Connection obtained for host: 0.0.0.0, port number 1527.
Sun Oct 22 18:39:20 CEST 2023 : Apache Derby Network Server - 10.15.2.0 - (1873585) shutdown
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- failsafe:3.1.2:verify (default) @ cargo-tracker ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:04 min
[INFO] Finished at: 2023-10-22T18:39:20+02:00
[INFO] ------------------------------------------------------------------------
```
Looks like some inter-tests dependency, not GF fault.

**Comment by hantsy** [comment]
Like other tests, the test used specific test purpose persistence config, https://github.com/hantsy/cargotracker/blob/master/src/test/java/org/eclipse/cargotracker/interfaces/booking/rest/CargoMonitoringServiceTest.java#L55, 

and it will drop and create db schema for every deployment. https://github.com/hantsy/cargotracker/blob/master/src/test/resources/test-persistence.xml#L8

**Comment by hantsy** [comment]
A possibility is table `cargo` is not ready when `SampleDataGenerator` is initialized.

**Comment by hantsy** [comment]
I think the problem is this line in the *test-persistence.xml*. 

```xml
<property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
```

Change `javax` to `jakarta`, it worked. But I do not know why other tests are working using the same persistence config. As a spec impl, eclipselink should keep the compatibility with old versions.

**Comment by pzygielo** [comment]
- https://github.com/eclipse-ee4j/eclipselink/issues/887
