### ISSUE TITLE
NoSuchFileException in console log when accessing deploying jsp

### ISSUE THREAD

**Issue by andresluuk** [eclipse-ee4j/glassfish#24683]
Did not happen on the previous glassfish minor version.

## Environment Details
* GlassFish Version 7.0.10
* JDK version: Temurin-11.0.14.1+1
* OS: windows/unix

----------

## Problem Description
When accessing JSP early on you get a SEVERE warning in the logs:
```
[#|2023-11-14T16:00:40.953439+02:00|INFO|GF 7.0.10|jakarta.enterprise.system.core|_ThreadID=92;_ThreadName=AutoDeployer;_LevelValue=800;|
  pa-ejb11Stateful-addMethod was successfully deployed in 3á539 milliseconds.|#]

[#|2023-11-14T16:00:40.957440+02:00|INFO|GF 7.0.10|jakarta.enterprise.system.tools.deployment.autodeploy|_ThreadID=92;_ThreadName=AutoDeployer;_LevelValue=800;_MessageID=NCLS-DEPLOYMENT-02035;|
  [AutoDeploy] Successfully autodeployed : C:\work\servers\glassfish7010\glassfish\domains\domain1\autodeploy\pa-ejb11Stateful-addMethod.ear.|#]

[#|2023-11-14T16:00:41.940389+02:00|SEVERE|GF 7.0.10|org.glassfish.wasp.compiler.Compiler|_ThreadID=52;_ThreadName=http-listener-1(2);_LevelValue=1000;|
  Failed to read attributes for file C:\work\servers\glassfish7010\glassfish\domains\domain1\generated\jsp\pa-ejb11Stateful-addMethod\test-web_war\org\apache\jsp\status_jsp.class
java.nio.file.NoSuchFileException: C:\work\servers\glassfish7010\glassfish\domains\domain1\generated\jsp\pa-ejb11Stateful-addMethod\test-web_war\org\apache\jsp\status_jsp.class
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at org.glassfish.wasp.compiler.Compiler.getLastModifiedTime(Compiler.java:610)
        at org.glassfish.wasp.compiler.Compiler.isOutDated(Compiler.java:472)
        at org.glassfish.wasp.compiler.Compiler.isOutDated(Compiler.java:439)
        at org.glassfish.wasp.JspCompilationContext.compile(JspCompilationContext.java:559)
        at org.glassfish.wasp.servlet.JspServletWrapper.service(JspServletWrapper.java:288)
        at org.glassfish.wasp.servlet.JspServlet.serviceJspFile(JspServlet.java:358)
        at org.glassfish.wasp.servlet.JspServlet.service(JspServlet.java:287)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1368)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:120)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:562)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:503)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:71)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:121)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:295)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:188)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:425)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

## Steps to reproduce
I deployd the provided ear (rename to ear) in autodeploy folder and accessed:
[pa-ejb11Stateful-addMethod.zip](https://github.com/eclipse-ee4j/glassfish/files/13349699/pa-ejb11Stateful-addMethod.zip)
http://localhost:8080/pa-ejb11Stateful-addMethod/status.jsp?3.054

## Impact of Issue
Log looks ugly.

**Comment by dmatej** [comment]
Ok, it is even already fixed in https://github.com/eclipse-ee4j/wasp/issues/64
We need to release WASP and update the dependency.

**Comment by arjantijms** [comment]
> We need to release WASP and update the dependency.

Indeed, sorry that this slipped though my review in last release. But it was fixed already. I'll stage a new WaSP version and do a PR for it here.
