### ISSUE TITLE
Embedded glassfish JAR doesn't contain JARS/RARS to support JMS

### ISSUE THREAD

**Issue by Blavo** [eclipse-ee4j/glassfish#24842]
Embedded Glassfish JAR doesn't contain the JARs / RARs to support JMS. On attempted use embedded glassfish excepts saying unable to create an active RAR with a cause of ClassNotFoundException naming com.sun.messaging.jms.ra.ResourceAdapter. In standard glassfish this class is in a JAR inside the imqjmsra.rar in the MQ directory. The (contents of) this RAR are not present in the 7.0.12 embedded glassfish JAR.

If, as I understand, the glassfish admin facility uses JMS then this takes out that facility as well.

## Environment Details
Glassfish 7.0.12

java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

Mac OS 12.4 (Monterey)

Database not relevant

----------

## Problem Description
As above.

Reliably reproducible

[StackTrace.txt](https://github.com/eclipse-ee4j/glassfish/files/14503102/StackTrace.txt)

## Steps to reproduce
1. Start an instance of glassfish embedded 
2. Note the JMS service port in the domain.xml in the following line:
      <system-property name="JMS_PROVIDER_PORT" description="Port Number that JMS Service will listen for remote clients connection." value="7454"></system-property>
3. In a browser enter http://localhost:nnnn where nnnn is the noted port number; this will trigger JMS (it seems to use lazy initialisation)
4. Glassfish will except as above

## Impact of Issue
I don't use JMS so this doesn't affect me directly. But I believe the glassfish admin facility uses JMS; the admin facility does not work for me against an embedded glassfish and this is probably the cause.

**Comment by dmatej** [comment]
That is quite good question, because embedded glassfish is quite specific. Years ago it was stripped from GF3. Naturally I don't think embedded glassfish should contain IMQ broker+JMS server, but throwing CNF exceptions is quite ugly. So it should support it OR it should nicely tell the user that JMS is not supported, but then we should document an example how to work with an external JMS with Embedded GlassFish.

That is quite a lot of work, I think ...

**Comment by OndroMih** [comment]
I investigated this a bit and the situation is a bit different in the latest version 7.0.23, at least for MessageDriven beans. The GlassFish Embedded JAR contains the OpenMQ client RAR but it loads it by 2 different classloaders, and then OpenMQ client gives error "Incompatible ResourceAdapter class=class com.sun.messaging.jms.ra.ResourceAdapter" because the given class is loaded by a different classloader.

When I compare the stacktrace given by @Blavo , it starts with 

```
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.initializeService(ActiveJmsResourceAdapter.java:2320)
	at com.sun.enterprise.v3.services.impl.ServiceInitializerFilter.handleAccept(ServiceInitializerFilter.java:105)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$7.execute(ExecutorResolver.java:74)
```

which looks like the resource adapter is initialized during a HTTP servlet and fails to find the ResourceAdapter class. In my case it's different and the application fails to deploy, starting with:

```
SEVERE: Exception while loading the app : EJB Container initialization error
com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Setup failed.
	at com.sun.enterprise.connectors.inbound.ConnectorMessageBeanClient.setup(ConnectorMessageBeanClient.java:177)
	at org.glassfish.ejb.mdb.MessageBeanContainer.<init>(MessageBeanContainer.java:223)
	at org.glassfish.ejb.mdb.MessageBeanContainerFactory.createContainer(MessageBeanContainerFactory.java:36)
	at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:192)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:265)
	at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:81)
	at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:198)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:310)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:529)
Caused by: jakarta.resource.ResourceException: MQJMSRA_AS4001: setResourceAdapter:Incompatible ResourceAdapter class=class com.sun.messaging.jms.ra.ResourceAdapter
	at com.sun.messaging.jms.ra.ActivationSpec.setResourceAdapter(ActivationSpec.java:295)
	at com.sun.enterprise.connectors.inbound.ConnectorMessageBeanClient.setup(ConnectorMessageBeanClient.java:163)
	... 28 more
```

In my case, it happens with the https://eclipse-ee4j.github.io/cargotracker/ app, which s a WAR. I deployed it from commands line, with: `java -jar glassfish-embedded-all-7.0.22.jar cargo-tracker.war`

@Blavo, could you test with GlassFish version 7.0.22 and share a reproducer app?

**Comment by hantsy** [comment]
@OndroMih, is there a workaround for this issue? I also encountered this issue when using GlassFish Embedded v8.

**Comment by OndroMih** [comment]
I don't know about any workaround yet, I'm sorry.
